# Generated by Django 5.1.5 on 2025-12-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventrole",
            name="role_name",
            field=models.CharField(
                choices=[
                    ("ASSISTANT_TEAM_LEADER", "Assistant Team Leader"),
                    ("CAMP_SERVANT", "Camp Servant"),
                    ("FACILITATOR", "Facilitator"),
                    ("GAMES_MASTER", "Games Master"),
                    ("COUPLE_COORDINATOR", "Couple Coordinator"),
                    ("SHARER", "Sharer"),
                    ("SPEAKER", "Speaker"),
                    ("TEAM_LEADER", "Team Leader"),
                    ("WORSHIP_LEADER", "Worship Leader"),
                    ("TECH_SUPPORT", "Tech Support"),
                    ("YOUTH_OBSERVER", "Youth Observer"),
                    ("CFC_OBSERVER", "CFC Observer"),
                    ("CFC_HELPER", "CFC Helper"),
                    ("CFC_COORDINATOR", "Coordinator"),
                    ("SFC_HELPER", "SFC Helper"),
                    ("VOLUNTEER", "Volunteer"),
                    ("ORGANIZER", "Organizer"),
                    ("SECRETARIAT", "Secretariat"),
                    ("PROGRAMME", "Programme"),
                    ("PFO", "PFO"),
                    ("PRODUCTION", "Production"),
                    ("LOGISTICS", "Logistics"),
                    ("MUSIC_MINISTRY", "Music Ministry"),
                    ("LITURGY", "Liturgy"),
                    ("COMPETITIONS", "Competitions"),
                    ("PROMOTIONS", "Promotions"),
                    ("DOCUMENTATION", "Documentation"),
                    ("EVENT_HEADS", "Event Heads"),
                    ("GENERAL_SERVICES", "General Services"),
                    ("CATERING", "Catering"),
                ],
                max_length=50,
                unique=True,
                verbose_name="role name",
            ),
        ),
    ]
