# Generated by Django 5.1.5 on 2025-09-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_eventdayattendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdayattendance",
            name="check_in_time",
            field=models.TimeField(blank=True, null=True, verbose_name="check-in time"),
        ),
        migrations.AlterField(
            model_name="eventdayattendance",
            name="check_out_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="check-out time"
            ),
        ),
        migrations.AlterField(
            model_name="eventdayattendance",
            name="day_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="attendance day"
            ),
        ),
    ]
