# Generated by Django 5.1.5 on 2025-09-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_eventdayattendance_check_in_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arealocation",
            name="active",
            field=models.BooleanField(default=True, verbose_name="is-active-area"),
        ),
        migrations.AddField(
            model_name="arealocation",
            name="active_members",
            field=models.IntegerField(
                default=0, verbose_name="number-of-active-members"
            ),
        ),
        migrations.AddField(
            model_name="arealocation",
            name="parish_communities",
            field=models.IntegerField(
                default=0, verbose_name="number-of-parish-communities"
            ),
        ),
        migrations.AddField(
            model_name="chapterlocation",
            name="active",
            field=models.BooleanField(default=True, verbose_name="is-active-chapter"),
        ),
        migrations.AddField(
            model_name="chapterlocation",
            name="active_members",
            field=models.IntegerField(
                default=0, verbose_name="number-of-active-members"
            ),
        ),
        migrations.AddField(
            model_name="chapterlocation",
            name="chapter_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chapterlocation",
            name="email_contact",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="chapter-contact-email",
            ),
        ),
        migrations.AddField(
            model_name="chapterlocation",
            name="established_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="established-date"
            ),
        ),
        migrations.AddField(
            model_name="chapterlocation",
            name="number_of_parishes",
            field=models.IntegerField(
                default=0, verbose_name="number-of-parish-communities"
            ),
        ),
        migrations.AddField(
            model_name="chapterlocation",
            name="phone_contact",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="chapter-contact-phone",
            ),
        ),
        migrations.AddField(
            model_name="clusterlocation",
            name="active",
            field=models.BooleanField(default=True, verbose_name="is-active-cluster"),
        ),
        migrations.AddField(
            model_name="clusterlocation",
            name="cluster_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusterlocation",
            name="established_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="established-date"
            ),
        ),
        migrations.AddField(
            model_name="clusterlocation",
            name="number_of_parishes",
            field=models.IntegerField(
                default=0, verbose_name="number-of-parish-communities"
            ),
        ),
        migrations.AddField(
            model_name="eventvenue",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="contact email"
            ),
        ),
        migrations.AddField(
            model_name="eventvenue",
            name="contact_phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="contact phone number",
            ),
        ),
    ]
