# Generated by Django 5.1.5 on 2025-09-23 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_arealocation_active_arealocation_active_members_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chapterlocation",
            name="adult_coordinators",
            field=models.ManyToManyField(
                blank=True,
                related_name="adult_coordinated_chapters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chapterlocation",
            name="volunteers",
            field=models.ManyToManyField(
                blank=True,
                related_name="volunteered_chapters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chapterlocation",
            name="youth_chapter_heads",
            field=models.ManyToManyField(
                blank=True, related_name="youth_chapters", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
