# Generated by Django 5.1.5 on 2025-09-24 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_chapterlocation_adult_coordinators_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="age_range",
            field=models.CharField(
                blank=True,
                help_text="E.g. 11-30",
                max_length=100,
                null=True,
                verbose_name="age range",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="expected_attendees",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="expected attendees",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="important_information",
            field=models.TextField(
                blank=True, null=True, verbose_name="important information"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="maximum_attendees",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="maximum attendees",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_closed",
            field=models.BooleanField(
                default=False, verbose_name="is registration closed"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="registration deadline"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_open",
            field=models.BooleanField(
                default=False, verbose_name="is registration open"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_open_date",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="registration open date"
            ),
        ),
        migrations.AddField(
            model_name="eventpaymentpackage",
            name="discounted_price",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Optional: discounted price in smallest currency unit",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="discounted price (in pence)",
            ),
        ),
        migrations.AddField(
            model_name="eventpaymentpackage",
            name="main_package",
            field=models.BooleanField(
                default=False,
                help_text="Mark this as the main package for the event (e.g., General Admission)",
                verbose_name="is main package",
            ),
        ),
        migrations.AddField(
            model_name="eventpaymentpackage",
            name="package_date_ends",
            field=models.DateField(
                blank=True, null=True, verbose_name="package end date"
            ),
        ),
        migrations.AddField(
            model_name="eventpaymentpackage",
            name="package_date_starts",
            field=models.DateField(
                auto_now=True, null=True, verbose_name="package start date"
            ),
        ),
        migrations.AddField(
            model_name="eventpaymentpackage",
            name="whats_included",
            field=models.TextField(
                blank=True,
                help_text="E.g., 'Includes access to all sessions, meals, and a T-shirt.' Ensure items are separated by a comma",
                null=True,
                verbose_name="what's included",
            ),
        ),
        migrations.AlterField(
            model_name="eventpaymentpackage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="E.g., short description of this package/ticket type",
                null=True,
                verbose_name="package description",
            ),
        ),
    ]
