# Generated by Django 5.1.5 on 2025-09-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_event_age_range_event_expected_attendees_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="registration_closed",
        ),
    ]
