# Generated by Django 5.1.5 on 2025-09-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_remove_event_registration_closed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpaymentmethod",
            name="iban",
        ),
        migrations.RemoveField(
            model_name="eventpaymentmethod",
            name="swift_bic",
        ),
        migrations.AddField(
            model_name="eventpaymentmethod",
            name="important_information",
            field=models.TextField(
                blank=True,
                help_text="E.g., 'Payments may take 2-3 business days to process.'",
                null=True,
                verbose_name="important information",
            ),
        ),
        migrations.AddField(
            model_name="eventpaymentmethod",
            name="reference_example",
            field=models.CharField(
                blank=True,
                help_text="E.g., 'John Smith'",
                max_length=100,
                null=True,
                verbose_name="reference example",
            ),
        ),
        migrations.AddField(
            model_name="eventpaymentmethod",
            name="reference_instruction",
            field=models.TextField(
                blank=True,
                help_text="E.g., 'Use your full name as reference'",
                max_length=100,
                null=True,
                verbose_name="reference instruction",
            ),
        ),
    ]
