# Generated by Django 5.1.5 on 2025-09-25 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_remove_eventpaymentmethod_iban_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpaymentmethod",
            name="currency",
            field=models.CharField(default="gbp", max_length=10),
        ),
        migrations.AddField(
            model_name="eventpaymentmethod",
            name="fee_add_on",
            field=models.IntegerField(
                default=0,
                help_text="Optional: additional fee in smallest currency unit (e.g., pence for GBP, cents for USD)",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="additional fee (in pence)",
            ),
        ),
        migrations.AddField(
            model_name="eventpaymentmethod",
            name="percentage_free",
            field=models.FloatField(
                default=0.0,
                help_text="Optional: percentage fee (e.g., 2.5 for 2.5%)",
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="percentage fee (%)",
            ),
        ),
    ]
