# Generated by Django 5.1.5 on 2025-09-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_eventpaymentmethod_currency_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventpaymentmethod",
            old_name="percentage_free",
            new_name="percentage_fee_add_on",
        ),
    ]
