# Generated by Django 5.1.5 on 2025-09-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0014_rename_percentage_free_eventpaymentmethod_percentage_fee_add_on",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="accessibility_requirements",
            field=models.TextField(
                blank=True, null=True, verbose_name="accessibility requirements"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="auto_approve_participants",
            field=models.BooleanField(
                default=False, verbose_name="auto approve participants"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "Planning"),
                    ("CONFIRMED", "Confirmed"),
                    ("ONGOING", "Ongoing"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("POSTPONED", "Postponed"),
                ],
                default="PLANNING",
                max_length=20,
                verbose_name="event status",
            ),
        ),
    ]
