# Generated by Django 5.1.5 on 2025-09-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_event_accessibility_requirements_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="accessibility_requirements",
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="accessibility_requirements",
            field=models.TextField(
                blank=True, null=True, verbose_name="accessibility requirements"
            ),
        ),
    ]
