# Generated by Django 5.1.5 on 2025-09-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_remove_event_accessibility_requirements_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventparticipant",
            name="dietary_restrictions",
        ),
        migrations.RemoveField(
            model_name="eventparticipant",
            name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="eventparticipant",
            name="emergency_phone",
        ),
        migrations.RemoveField(
            model_name="eventparticipant",
            name="special_needs",
        ),
    ]
