# Generated by Django 5.1.5 on 2025-09-25 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_remove_eventparticipant_dietary_restrictions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpayment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant_event_payments",
                to="events.eventparticipant",
            ),
        ),
    ]
