# Generated by Django 5.1.5 on 2025-09-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_alter_eventpayment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipant",
            name="news_letter_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="terms_and_conditions_consent",
            field=models.BooleanField(default=False),
        ),
    ]
