# Generated by Django 5.1.5 on 2025-09-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_eventparticipant_special_requests_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="what_to_bring",
            field=models.TextField(blank=True, null=True, verbose_name="what to bring"),
        ),
    ]
