# Generated by Django 5.1.5 on 2025-09-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_event_what_to_bring"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="payment_deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="payment deadline"
            ),
        ),
    ]
