# Generated by Django 5.1.5 on 2025-10-01 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_event_payment_deadline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="participantquestion",
            name="answered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user who answered the question",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answered_participant_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
