# Generated by Django 5.1.5 on 2025-10-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_participantquestion_answered_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpayment",
            name="bank_reference",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                unique=True,
                verbose_name="Payment Reference",
            ),
        ),
    ]
