# Generated by Django 5.1.5 on 2025-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_eventpayment_bank_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="format_verifier",
            field=models.CharField(
                blank=True,
                help_text="For requiring existing id, this can be used to match a given format I.e. %%%%-%%%%-%%%%",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="required_existing_id",
            field=models.BooleanField(
                default=False,
                help_text="Upon registration, the user must enter a specific ID that is linked to another system E.g. OGD",
            ),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="event_pax_id",
            field=models.CharField(
                blank=True, null=True, unique=True, verbose_name="Participant ID"
            ),
        ),
    ]
