# Generated by Django 5.1.5 on 2025-10-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0025_event_format_verifier_event_required_existing_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="existing_id_description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="existing_id_name",
            field=models.CharField(
                blank=True,
                help_text="existing name for this id E.g. Members-ID",
                max_length=100,
                null=True,
            ),
        ),
    ]
