# Generated by Django 5.1.5 on 2025-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_event_existing_id_description_event_existing_id_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipant",
            name="secondary_reference_id",
            field=models.CharField(
                blank=True,
                help_text="acts as a secondary id option and is good for backwards compatibility for exisiting database references",
                null=True,
                verbose_name="backup reference id",
            ),
        ),
    ]
