# Generated by Django 5.1.5 on 2025-10-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0027_eventparticipant_secondary_reference_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdayattendance",
            name="stale",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="marks this attendance object as stale and can no longer be updated",
            ),
        ),
    ]
