# Generated by Django 5.1.5 on 2025-10-10 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0028_eventdayattendance_stale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount in pounds (e.g., 30.00 for £30.00)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="eventpaymentmethod",
            name="fee_add_on",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Optional: additional fee (e.g., 2.50 for £2.50)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="additional fee",
            ),
        ),
        migrations.AlterField(
            model_name="eventpaymentpackage",
            name="discounted_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Optional: discounted price in pounds (e.g., 20.00 for £20.00)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="discounted price",
            ),
        ),
        migrations.AlterField(
            model_name="eventpaymentpackage",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price in pounds (e.g., 25.00 for £25.00)",
                max_digits=10,
                verbose_name="price",
            ),
        ),
    ]
