# Generated by Django 5.1.5 on 2025-11-01 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0029_alter_eventpayment_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for this refund",
                        max_length=100,
                        unique=True,
                        verbose_name="refund reference",
                    ),
                ),
                (
                    "event_payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount to refund for event registration",
                        max_digits=10,
                        verbose_name="event registration refund amount",
                    ),
                ),
                (
                    "product_payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount to refund for merchandise purchases",
                        max_digits=10,
                        verbose_name="merchandise refund amount",
                    ),
                ),
                (
                    "total_refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount to be refunded",
                        max_digits=10,
                        verbose_name="total refund amount",
                    ),
                ),
                ("currency", models.CharField(default="gbp", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Processing"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PROCESSED", "Refund Processed"),
                            ("CANCELLED", "Refund Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="refund status",
                    ),
                ),
                (
                    "removal_reason",
                    models.TextField(
                        help_text="Reason provided when participant was removed from event",
                        verbose_name="reason for removal",
                    ),
                ),
                (
                    "processing_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about refund processing",
                        null=True,
                        verbose_name="processing notes",
                    ),
                ),
                (
                    "participant_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address at time of removal",
                        max_length=254,
                        null=True,
                        verbose_name="participant email",
                    ),
                ),
                (
                    "organizer_contact_email",
                    models.EmailField(
                        help_text="Email address for refund inquiries",
                        max_length=254,
                        verbose_name="organizer contact email",
                    ),
                ),
                (
                    "original_payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Payment method used for original transaction",
                        max_length=50,
                        null=True,
                        verbose_name="original payment method",
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        blank=True,
                        help_text="Method used to process refund",
                        max_length=50,
                        null=True,
                        verbose_name="refund method",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when refund was marked as processed",
                        null=True,
                        verbose_name="processed at",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_refunds",
                        to="events.event",
                        verbose_name="event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="events.eventparticipant",
                        verbose_name="participant",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_processed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="processed by",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_initiated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="removed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant Refund",
                "verbose_name_plural": "Participant Refunds",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="events_part_status_c827f2_idx",
                    ),
                    models.Index(
                        fields=["event", "status"],
                        name="events_part_event_i_3e51f6_idx",
                    ),
                    models.Index(
                        fields=["participant"], name="events_part_partici_1ab070_idx"
                    ),
                ],
            },
        ),
    ]
