# Generated by Django 5.1.5 on 2025-11-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0030_participantrefund"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpayment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participant_event_payments",
                to="events.eventparticipant",
            ),
        ),
    ]
