# Generated by Django 5.1.5 on 2025-11-06 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0031_alter_eventpayment_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="organisation name"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, null=True, verbose_name="organisation description"
                    ),
                ),
                (
                    "landing_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="organisations/landing-images/",
                        verbose_name="organisation landing image",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="organisations/logos/",
                        verbose_name="organisation logo",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="organsiation email",
                    ),
                ),
                (
                    "external_link",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="organsiation website link",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonationPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_payment_tracking_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for this payment (e.g., UUID or custom format)",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="payment tracking number",
                    ),
                ),
                (
                    "bank_reference",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        null=True,
                        unique=True,
                        verbose_name="Payment Reference",
                    ),
                ),
                (
                    "stripe_payment_intent",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount in pounds (e.g., 30.00 for £30.00)",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="gbp", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="Set to true when payment is verified/confirmed",
                        verbose_name="payment verified",
                    ),
                ),
                (
                    "pay_to_event",
                    models.BooleanField(
                        default=True,
                        help_text="pay this donation to the event being held",
                        verbose_name="pay to event",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donation_payments",
                        to="events.event",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donation_payments",
                        to="events.eventpaymentmethod",
                        verbose_name="payment method",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participant_donation_payments",
                        to="events.eventparticipant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Payment",
                "verbose_name_plural": "Event Payments",
            },
        ),
        migrations.CreateModel(
            name="OrganisationSocialMediaLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="organisation social media type"
                    ),
                ),
                (
                    "external_link",
                    models.CharField(
                        max_length=100, verbose_name="organsiation website link"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, null=True, verbose_name="organisation description"
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_links",
                        to="events.organisation",
                    ),
                ),
            ],
        ),
    ]
