# Generated by Django 5.1.5 on 2025-11-06 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0032_organisation_donationpayment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donationpayment",
            options={
                "verbose_name": "Donation Payment",
                "verbose_name_plural": "Donation Payments",
            },
        ),
        migrations.RemoveField(
            model_name="donationpayment",
            name="pay_to_event",
        ),
        migrations.RemoveField(
            model_name="donationpayment",
            name="verified",
        ),
        migrations.AlterField(
            model_name="donationpayment",
            name="method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donation_method_payments",
                to="events.eventpaymentmethod",
                verbose_name="payment method",
            ),
        ),
    ]
