# Generated by Django 5.1.5 on 2025-11-06 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0033_alter_donationpayment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donationpayment",
            options={
                "verbose_name": "Event Payment",
                "verbose_name_plural": "Event Payments",
            },
        ),
        migrations.AddField(
            model_name="donationpayment",
            name="pay_to_event",
            field=models.BooleanField(
                default=True,
                help_text="pay this donation to the event being held",
                verbose_name="pay to event",
            ),
        ),
        migrations.AddField(
            model_name="donationpayment",
            name="verified",
            field=models.BooleanField(
                default=False,
                help_text="Set to true when payment is verified/confirmed",
                verbose_name="payment verified",
            ),
        ),
        migrations.AlterField(
            model_name="donationpayment",
            name="method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donation_payments",
                to="events.eventpaymentmethod",
                verbose_name="payment method",
            ),
        ),
    ]
