# Generated by Django 5.1.5 on 2025-11-06 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0034_alter_donationpayment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceTeamPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permission id",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin - Full Access"),
                            ("MERCH_ONLY", "Merchandise Only"),
                            ("SCANNER_ONLY", "Scanner Only"),
                            ("PARTICIPANT_MANAGEMENT", "Participant Management"),
                            ("CUSTOM", "Custom Permissions"),
                        ],
                        default="CUSTOM",
                        help_text="Role-based permission template. CUSTOM allows granular control.",
                        max_length=30,
                        verbose_name="permission role",
                    ),
                ),
                (
                    "can_view_participants",
                    models.BooleanField(
                        default=False,
                        help_text="Can view participant list and details",
                        verbose_name="can view participants",
                    ),
                ),
                (
                    "can_edit_participants",
                    models.BooleanField(
                        default=False,
                        help_text="Can edit participant details, registration info",
                        verbose_name="can edit participants",
                    ),
                ),
                (
                    "can_remove_participants",
                    models.BooleanField(
                        default=False,
                        help_text="Can remove participants from event",
                        verbose_name="can remove participants",
                    ),
                ),
                (
                    "can_add_participants",
                    models.BooleanField(
                        default=False,
                        help_text="Can add new participants to event",
                        verbose_name="can add participants",
                    ),
                ),
                (
                    "can_view_payments",
                    models.BooleanField(
                        default=False,
                        help_text="Can view payment records",
                        verbose_name="can view payments",
                    ),
                ),
                (
                    "can_approve_payments",
                    models.BooleanField(
                        default=False,
                        help_text="Can verify and approve event payments",
                        verbose_name="can approve payments",
                    ),
                ),
                (
                    "can_process_refunds",
                    models.BooleanField(
                        default=False,
                        help_text="Can process participant refunds",
                        verbose_name="can process refunds",
                    ),
                ),
                (
                    "can_view_merch",
                    models.BooleanField(
                        default=False,
                        help_text="Can view merchandise and orders",
                        verbose_name="can view merchandise",
                    ),
                ),
                (
                    "can_manage_merch",
                    models.BooleanField(
                        default=False,
                        help_text="Can create, edit, delete merchandise and manage orders",
                        verbose_name="can manage merchandise",
                    ),
                ),
                (
                    "can_approve_merch_payments",
                    models.BooleanField(
                        default=False,
                        help_text="Can verify merchandise payments",
                        verbose_name="can approve merch payments",
                    ),
                ),
                (
                    "can_access_checkin",
                    models.BooleanField(
                        default=False,
                        help_text="Can access event check-in scanner and dashboard",
                        verbose_name="can access check-in",
                    ),
                ),
                (
                    "can_access_live_dashboard",
                    models.BooleanField(
                        default=False,
                        help_text="Can access real-time event dashboard and analytics",
                        verbose_name="can access live dashboard",
                    ),
                ),
                (
                    "can_edit_event_details",
                    models.BooleanField(
                        default=False,
                        help_text="Can edit event basic information, venue, dates",
                        verbose_name="can edit event details",
                    ),
                ),
                (
                    "can_manage_service_team",
                    models.BooleanField(
                        default=False,
                        help_text="Can add/remove service team members",
                        verbose_name="can manage service team",
                    ),
                ),
                (
                    "can_manage_permissions",
                    models.BooleanField(
                        default=False,
                        help_text="Can set permissions for other service team members",
                        verbose_name="can manage permissions",
                    ),
                ),
                (
                    "can_manage_resources",
                    models.BooleanField(
                        default=False,
                        help_text="Can add/edit/delete event resources",
                        verbose_name="can manage resources",
                    ),
                ),
                (
                    "can_manage_questions",
                    models.BooleanField(
                        default=False,
                        help_text="Can view and respond to participant questions",
                        verbose_name="can manage questions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="granted by",
                    ),
                ),
                (
                    "service_team_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="events.eventserviceteammember",
                        verbose_name="service team member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Team Permission",
                "verbose_name_plural": "Service Team Permissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
