# Generated by Django 5.1.5 on 2025-11-08 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0035_serviceteampermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                help_text="defines the organisation attached to the event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.organisation",
                verbose_name="event organisation",
            ),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                help_text="defines the organisation attached to the event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_participants",
                to="events.organisation",
                verbose_name="event organisation",
            ),
        ),
    ]
