# Generated by Django 5.1.5 on 2025-11-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0036_event_organisation_eventparticipant_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="force_participant_organisation",
            field=models.BooleanField(
                default=True,
                help_text="On registration, participants that register to this event will use the organisation defined above unless set otherwise. set to False to allow people from other organisations to define themelves on registration",
            ),
        ),
    ]
