# Generated by Django 5.1.5 on 2025-11-08 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0037_event_force_participant_organisation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="approval_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes from the approver to the event creator",
                null=True,
                verbose_name="approval notes",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the event was approved",
                null=True,
                verbose_name="approval timestamp",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved this event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="approved by",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="rejected",
            field=models.BooleanField(
                default=False,
                help_text="Whether this event has been rejected by an approver",
                verbose_name="event rejected",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for rejecting this event",
                null=True,
                verbose_name="rejection reason",
            ),
        ),
    ]
