# Generated by Django 5.1.5 on 2025-11-11 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0038_event_approval_notes_event_approved_at_and_more"),
        ("shop", "0016_productpaymentmethod_refund_contact_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participantrefund",
            name="organizer_contact_email",
        ),
        migrations.RemoveField(
            model_name="participantrefund",
            name="removal_reason",
        ),
        migrations.AddField(
            model_name="event",
            name="refund_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for processing refunds. If not set, defaults to payment_deadline. No refunds after event starts.",
                null=True,
                verbose_name="refund deadline",
            ),
        ),
        migrations.AddField(
            model_name="eventpaymentmethod",
            name="refund_contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address participants should contact for refund inquiries (leave blank to use secretariat)",
                max_length=254,
                null=True,
                verbose_name="refund contact email",
            ),
        ),
        migrations.AddField(
            model_name="eventpaymentmethod",
            name="refund_processing_time",
            field=models.CharField(
                blank=True,
                help_text="E.g., '5-7 business days' - displayed to participants",
                max_length=200,
                null=True,
                verbose_name="refund processing time",
            ),
        ),
        migrations.AddField(
            model_name="eventpaymentmethod",
            name="supports_automatic_refunds",
            field=models.BooleanField(
                default=False,
                help_text="Enable for Stripe/PayPal. Disable for manual methods like bank transfer or cash.",
                verbose_name="supports automatic refunds",
            ),
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="bank_account_name",
            field=models.CharField(
                blank=True,
                help_text="Participant's bank account name for manual refunds",
                max_length=200,
                null=True,
                verbose_name="bank account name",
            ),
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="bank_account_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="bank account number"
            ),
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="bank_sort_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="bank sort code"
            ),
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="event_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="events.eventpayment",
                verbose_name="original event payment",
            ),
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="is_automatic_refund",
            field=models.BooleanField(
                default=False,
                help_text="True if refund can be processed automatically via Stripe/PayPal",
                verbose_name="automatic refund",
            ),
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="participant_name",
            field=models.CharField(
                blank=True,
                help_text="Full name at time of refund creation",
                max_length=200,
                null=True,
                verbose_name="participant name",
            ),
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="participant_notified",
            field=models.BooleanField(
                default=False,
                help_text="Whether participant has been notified about the refund",
                verbose_name="participant notified",
            ),
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="product_payments",
            field=models.ManyToManyField(
                blank=True,
                related_name="refunds",
                to="shop.productpayment",
                verbose_name="original product payments",
            ),
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="refund_contact_email",
            field=models.EmailField(
                default="default@gmail.com",
                help_text="Email address participants should contact for refund inquiries (secretariat/organizer)",
                max_length=254,
                verbose_name="refund contact email",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="refund_reason",
            field=models.CharField(
                choices=[
                    ("USER_REQUESTED", "User Requested"),
                    ("EVENT_CANCELLED", "Event Cancelled"),
                    ("ADMIN_DECISION", "Administrative Decision"),
                    ("DUPLICATE", "Duplicate Payment"),
                    ("REMOVED", "Participant Removed"),
                    ("OTHER", "Other"),
                ],
                default="REMOVED",
                max_length=50,
                verbose_name="refund reason",
            ),
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="removal_reason_details",
            field=models.TextField(
                default="default reason",
                help_text="Detailed explanation for the refund",
                verbose_name="detailed reason",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="secretariat_notified",
            field=models.BooleanField(
                default=False,
                help_text="Whether secretariat has been notified about manual refund",
                verbose_name="secretariat notified",
            ),
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="stripe_failure_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason if Stripe refund failed",
                null=True,
                verbose_name="Stripe failure reason",
            ),
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="stripe_refund_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe refund ID if processed through Stripe",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Stripe refund ID",
            ),
        ),
        migrations.AlterField(
            model_name="participantrefund",
            name="participant_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address at time of refund creation",
                max_length=254,
                null=True,
                verbose_name="participant email",
            ),
        ),
        migrations.AlterField(
            model_name="participantrefund",
            name="refund_method",
            field=models.CharField(
                blank=True,
                help_text="Method used to process refund (Stripe, Bank Transfer, etc.)",
                max_length=50,
                null=True,
                verbose_name="refund method",
            ),
        ),
        migrations.AlterField(
            model_name="participantrefund",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds_initiated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="initiated by",
            ),
        ),
        migrations.AlterField(
            model_name="participantrefund",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Processing"),
                    ("IN_PROGRESS", "In Progress"),
                    ("PROCESSED", "Refund Processed"),
                    ("CANCELLED", "Refund Cancelled"),
                    ("FAILED", "Refund Failed"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="refund status",
            ),
        ),
        migrations.AddIndex(
            model_name="participantrefund",
            index=models.Index(
                fields=["refund_reference"], name="events_part_refund__c87b79_idx"
            ),
        ),
    ]
