# Generated by Django 5.1.5 on 2025-11-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0039_remove_participantrefund_organizer_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventpaymentmethod",
            options={
                "verbose_name": "Event Donations Method",
                "verbose_name_plural": "Event Donations Methods",
            },
        ),
    ]
