# Generated by Django 5.1.5 on 2025-11-12 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0040_alter_eventpaymentmethod_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventserviceteammember",
            name="product_discount_type",
            field=models.CharField(
                blank=True,
                choices=[("PERCENTAGE", "Percentage"), ("FIXED", "Fixed Amount")],
                help_text="Type of discount for products",
                max_length=20,
                null=True,
                verbose_name="product discount type",
            ),
        ),
        migrations.AddField(
            model_name="eventserviceteammember",
            name="product_discount_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Discount value for products (percentage or fixed amount)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="product discount value",
            ),
        ),
        migrations.AddField(
            model_name="eventserviceteammember",
            name="registration_discount_type",
            field=models.CharField(
                blank=True,
                choices=[("PERCENTAGE", "Percentage"), ("FIXED", "Fixed Amount")],
                help_text="Type of discount for event registration",
                max_length=20,
                null=True,
                verbose_name="discount type",
            ),
        ),
        migrations.AddField(
            model_name="eventserviceteammember",
            name="registration_discount_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Discount value (percentage or fixed amount in currency)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="discount value",
            ),
        ),
    ]
