# Generated by Django 5.1.5 on 2025-11-12 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0041_eventserviceteammember_product_discount_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_discount_type",
            field=models.CharField(
                blank=True,
                choices=[("PERCENTAGE", "Percentage"), ("FIXED", "Fixed Amount")],
                help_text="Default discount type for event registration (can be overridden per service team member)",
                max_length=20,
                null=True,
                verbose_name="registration discount type",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_discount_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Default discount value for registration (percentage 0-100 or fixed amount in currency)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="registration discount value",
            ),
        ),
    ]
