# Generated by Django 5.1.5 on 2025-11-12 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0042_event_registration_discount_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrole",
            name="product_discount_type",
            field=models.CharField(
                blank=True,
                choices=[("PERCENTAGE", "Percentage"), ("FIXED", "Fixed Amount")],
                help_text="Default discount type for this role's product purchases",
                max_length=20,
                null=True,
                verbose_name="product discount type",
            ),
        ),
        migrations.AddField(
            model_name="eventrole",
            name="product_discount_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Default discount value for products (percentage or fixed amount)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="product discount value",
            ),
        ),
        migrations.AddField(
            model_name="eventrole",
            name="registration_discount_type",
            field=models.CharField(
                blank=True,
                choices=[("PERCENTAGE", "Percentage"), ("FIXED", "Fixed Amount")],
                help_text="Default discount type for this role's registration",
                max_length=20,
                null=True,
                verbose_name="registration discount type",
            ),
        ),
        migrations.AddField(
            model_name="eventrole",
            name="registration_discount_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Default discount value for this role (percentage 0-100 or fixed amount)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="registration discount value",
            ),
        ),
    ]
