# Generated by Django 5.1.5 on 2025-11-12 20:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0043_eventrole_product_discount_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventrole",
            name="product_discount_type",
        ),
        migrations.RemoveField(
            model_name="eventrole",
            name="product_discount_value",
        ),
        migrations.RemoveField(
            model_name="eventrole",
            name="registration_discount_type",
        ),
        migrations.RemoveField(
            model_name="eventrole",
            name="registration_discount_value",
        ),
        migrations.CreateModel(
            name="EventRoleDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="role discount id",
                    ),
                ),
                (
                    "registration_discount_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED", "Fixed Amount"),
                        ],
                        help_text="Discount type for registration for this role in this event",
                        max_length=20,
                        null=True,
                        verbose_name="registration discount type",
                    ),
                ),
                (
                    "registration_discount_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Discount value for registration (percentage 0-100 or fixed amount)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="registration discount value",
                    ),
                ),
                (
                    "product_discount_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED", "Fixed Amount"),
                        ],
                        help_text="Discount type for products for this role in this event",
                        max_length=20,
                        null=True,
                        verbose_name="product discount type",
                    ),
                ),
                (
                    "product_discount_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Discount value for products (percentage or fixed amount)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="product discount value",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_discounts",
                        to="events.event",
                        verbose_name="event",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_discounts",
                        to="events.eventrole",
                        verbose_name="role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Role Discount",
                "verbose_name_plural": "Event Role Discounts",
                "ordering": ["event", "role"],
                "unique_together": {("event", "role")},
            },
        ),
    ]
