# Generated by Django 5.1.5 on 2025-11-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0045_event_product_discount_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="product_purchase_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for purchasing products related to the event",
                null=True,
                verbose_name="product purchase deadline",
            ),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="allowed_to_buy_products",
            field=models.BooleanField(
                default=True,
                help_text="Defines if this participant is allowed to purchase products related to the event",
                verbose_name="allowed to buy products",
            ),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="is_visible",
            field=models.BooleanField(
                default=True,
                help_text="Defines if this participant is visible in participant lists",
                verbose_name="is visible",
            ),
        ),
        migrations.AddField(
            model_name="serviceteampermission",
            name="can_delete_event",
            field=models.BooleanField(
                default=False,
                help_text="Can delete the event entirely",
                verbose_name="can delete event",
            ),
        ),
        migrations.AddField(
            model_name="serviceteampermission",
            name="can_publish_event",
            field=models.BooleanField(
                default=False,
                help_text="Can publish the event to make it live",
                verbose_name="can publish event",
            ),
        ),
        migrations.AddField(
            model_name="serviceteampermission",
            name="can_view_event_payment_statistics",
            field=models.BooleanField(
                default=False,
                help_text="Can view overall payment statistics and reports",
                verbose_name="can view payment statistics",
            ),
        ),
        migrations.AddField(
            model_name="serviceteampermission",
            name="can_view_management_dashboard",
            field=models.BooleanField(
                default=False,
                help_text="Can access the event management dashboard",
                verbose_name="can view management dashboard",
            ),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="participant_type",
            field=models.CharField(
                choices=[
                    ("PARTICIPANT", "Participant"),
                    ("SERVICE_TEAM", "Service_team"),
                    ("OBSERVER", "Observer"),
                    ("GUEST", "Guest"),
                    ("VISITOR", "Visitor"),
                    ("SPEAKER", "Speaker"),
                    ("VOLUNTEER", "Volunteer"),
                ],
                default="PARTICIPANT",
                max_length=20,
                verbose_name="participant type",
            ),
        ),
        migrations.AlterField(
            model_name="serviceteampermission",
            name="can_view_payments",
            field=models.BooleanField(
                default=False,
                help_text="Can view participant payment records",
                verbose_name="can view participant payments",
            ),
        ),
    ]
