# Generated by Django 5.1.5 on 2025-11-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0046_event_product_purchase_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="merch_sale_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When merchandise sales close. If not set, defaults to payment_deadline or event end_date.",
                null=True,
                verbose_name="merchandise sale end date",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="merch_sale_start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When merchandise becomes available for purchase. If not set, merch is available once registration opens.",
                null=True,
                verbose_name="merchandise sale start date",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="refunds_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether refunds are allowed for this event. If disabled, refund deadline is not applicable.",
                verbose_name="refunds enabled",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="product_purchase_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for purchasing products related to the event (deprecated - use merch_sale_end_date)",
                null=True,
                verbose_name="product purchase deadline",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="refund_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for requesting refunds. Only applicable if refunds are enabled. If not set, defaults to payment_deadline.",
                null=True,
                verbose_name="refund deadline",
            ),
        ),
    ]
