# Generated by Django 5.1.5 on 2025-11-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0047_event_merch_sale_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="merch_grace_period",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, users cannot create a new order while they have a pending/unverified order. They must wait for the current order to complete.",
                verbose_name="merchandise grace period",
            ),
        ),
    ]
