# Generated by Django 5.1.5 on 2025-11-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0048_event_merch_grace_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date_for_deletion",
            field=models.DateTimeField(
                blank=True,
                help_text="If event is marked for deletion, this is the date when it will be permanently deleted.",
                null=True,
                verbose_name="date for deletion",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "Planning"),
                    ("CONFIRMED", "Confirmed"),
                    ("ONGOING", "Ongoing"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("POSTPONED", "Postponed"),
                    ("REJECTED", "Rejected"),
                    ("PENDING_DELETION", "Pending Deletion"),
                    ("DELETED", "Deleted"),
                ],
                default="PLANNING",
                max_length=20,
                verbose_name="event status",
            ),
        ),
    ]
