# Generated by Django 5.1.5 on 2025-11-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0049_event_date_for_deletion_alter_event_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("REFUND_PROCESSING", "Refund Processing"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
