# Generated by Django 5.1.5 on 2025-12-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0050_alter_eventpayment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donationpayment",
            options={
                "verbose_name": "Donation Payment",
                "verbose_name_plural": "Donation Payments",
            },
        ),
    ]
