# Generated by Django 5.1.5 on 2025-12-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0051_alter_donationpayment_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participantrefund",
            name="bank_account_name",
        ),
        migrations.RemoveField(
            model_name="participantrefund",
            name="bank_account_number",
        ),
        migrations.RemoveField(
            model_name="participantrefund",
            name="bank_sort_code",
        ),
        migrations.RemoveField(
            model_name="participantrefund",
            name="event_payment_amount",
        ),
        migrations.RemoveField(
            model_name="participantrefund",
            name="product_payment_amount",
        ),
        migrations.RemoveField(
            model_name="participantrefund",
            name="product_payments",
        ),
        migrations.RemoveField(
            model_name="participantrefund",
            name="total_refund_amount",
        ),
        migrations.AddField(
            model_name="participantrefund",
            name="refund_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount to refund for event registration only. Merchandise refunds tracked separately via OrderRefund.",
                max_digits=10,
                verbose_name="event registration refund amount",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="participantrefund",
            name="event_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participant_refunds",
                to="events.eventpayment",
                verbose_name="original event payment",
            ),
        ),
    ]
