# Generated by Django 5.1.5 on 2025-12-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0052_remove_participantrefund_bank_account_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participantrefund",
            old_name="stripe_refund_id",
            new_name="stripe_refund_intent",
        ),
    ]
