# Generated by Django 5.1.5 on 2025-12-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0053_rename_stripe_refund_id_participantrefund_stripe_refund_intent",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="participantrefund",
            old_name="stripe_refund_intent",
            new_name="stripe_refund_id",
        ),
    ]
