# Generated by Django 5.1.5 on 2025-12-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0054_rename_stripe_refund_intent_participantrefund_stripe_refund_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "Planning"),
                    ("CONFIRMED", "Confirmed"),
                    ("ONGOING", "Ongoing"),
                    ("COMPLETED", "Completed"),
                    ("ARCHIVED", "Archived"),
                    ("CANCELLED", "Cancelled"),
                    ("POSTPONED", "Postponed"),
                    ("REJECTED", "Rejected"),
                    ("PENDING_DELETION", "Pending Deletion"),
                    ("DELETED", "Deleted"),
                ],
                default="PLANNING",
                max_length=20,
                verbose_name="event status",
            ),
        ),
    ]
