# Generated by Django 5.1.5 on 2025-12-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_convert_time_to_datetime"),
        ("events", "0055_alter_event_status"),
    ]

    operations = []
