# Generated by Django 5.1.5 on 2025-09-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alergies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alergy_name",
                    models.CharField(max_length=200, verbose_name="name of alergy"),
                ),
                (
                    "alergy_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="alergy description"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="last name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="middle name"
                    ),
                ),
                (
                    "preferred_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="preferred name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="emergency contact email address",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="emergency contact phone number",
                    ),
                ),
                (
                    "contact_relationship",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MOTHER", "Mother"),
                            ("FATHER", "Father"),
                            ("GUARDIAN", "Guardian"),
                            ("SPOUSE", "Spouse"),
                            ("HUSBAND", "Husband"),
                            ("WIFE", "Wife"),
                            ("BROTHER", "Brother"),
                            ("SISTER", "Sister"),
                        ],
                        null=True,
                        verbose_name="emergency contact relationship",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="communityuser",
            name="alergies",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="users.alergies",
                verbose_name="Individual alergies",
            ),
        ),
        migrations.AddField(
            model_name="communityuser",
            name="emergency_contacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_emergency_contacts",
                to="users.emergencycontact",
                verbose_name="Emergency contacts",
            ),
        ),
    ]
