# Generated by Django 5.1.5 on 2025-09-06 11:16

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cluster_id",
                    models.CharField(max_length=2, verbose_name="cluster-name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CountryLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True, unique=True
                    ),
                ),
                (
                    "general_sector",
                    models.CharField(
                        choices=[
                            ("EUROPE", "Europe"),
                            ("ASIA", "Asia"),
                            ("NORTH_AMERICA", "North America"),
                            ("CENTRAL_AMERICA", "Central America"),
                            ("SOUTH_AMERICA", "South America"),
                            ("AFRICA", "Africa"),
                            ("OCEANIA", "Oceania"),
                            ("MIDDLE_EAST", "Middle East"),
                        ],
                        verbose_name="general world sector",
                    ),
                ),
                (
                    "specific_sector",
                    models.CharField(
                        choices=[
                            ("NORTH_EUROPE", "Northern Europe"),
                            ("SOUTH_EUROPE", "Southern Europe"),
                            ("WEST_EUROPE", "Western Europe"),
                            ("EAST_EUROPE", "Eastern Europe"),
                            ("CENTRAL_EUROPE", "Central Europe"),
                            ("EAST_ASIA", "East Asia"),
                            ("SOUTH_ASIA", "South Asia"),
                            ("SOUTHEAST_ASIA", "Southeast Asia"),
                            ("CENTRAL_ASIA", "Central Asia"),
                            ("WEST_ASIA", "Western Asia"),
                            ("NORTH_AMERICA", "North America"),
                            ("CENTRAL_AMERICA", "Central America"),
                            ("CARIBBEAN", "Caribbean"),
                            ("SOUTH_AMERICA_NORTH", "Northern South America"),
                            ("SOUTH_AMERICA_SOUTH", "Southern South America"),
                            ("ANDES", "Andean Region"),
                            ("CONO_SUR", "Cono Sur (Southern Cone)"),
                            ("NORTH_AFRICA", "North Africa"),
                            ("WEST_AFRICA", "West Africa"),
                            ("EAST_AFRICA", "East Africa"),
                            ("CENTRAL_AFRICA", "Central Africa"),
                            ("SOUTH_AFRICA", "Southern Africa"),
                            ("AUSTRALIA_NEWZEALAND", "Australia & New Zealand"),
                            ("MELANESIA", "Melanesia"),
                            ("MICRONESIA", "Micronesia"),
                            ("POLYNESIA", "Polynesia"),
                            ("GULF", "Gulf States"),
                            ("LEVANT", "Levant"),
                            ("PERSIAN", "Persian Region"),
                        ],
                        verbose_name="specific world sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YouthCampRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        choices=[
                            ("ASSISTANT_TEAM_LEADER", "Assistant Team Leader"),
                            ("CAMP_SERVANT", "Camp Servant"),
                            ("SECRETARIAT", "Secretariat"),
                            ("FACILITATOR", "Facilitator"),
                            ("GAMES_MASTER", "Games Master"),
                            ("COUPLE_COORDINATOR", "Couple Coordinator"),
                            ("MUSIC_MINISTRY", "Music Ministry"),
                            ("SHARER", "Sharer"),
                            ("SPEAKER", "Speaker"),
                            ("TEAM_LEADER", "Team Leader"),
                            ("WORSHIP_LEADER", "Worship Leader"),
                            ("TECH_SUPPORT", "Tech Support"),
                            ("YOUTH_OBSERVER", "Youth Observer"),
                            ("CFC_OBSERVER", "CFC Observer"),
                            ("CFC_HELPER", "CFC Helper"),
                            ("SFC_HELPER", "SFC Helper"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="role name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="role description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Youth Camp Role",
                "verbose_name_plural": "Youth Camp Roles",
                "ordering": ["role_name"],
            },
        ),
        migrations.CreateModel(
            name="ChapterLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chapter_id",
                    models.CharField(blank=True, null=True, verbose_name="chapter-id"),
                ),
                (
                    "chapter_name",
                    models.CharField(max_length=150, verbose_name="name-of-chapter"),
                ),
                (
                    "chapter_code",
                    models.CharField(
                        max_length=3, null=True, verbose_name="chapter-code"
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="events.clusterlocation",
                    ),
                ),
            ],
            options={
                "unique_together": {("chapter_name", "cluster")},
            },
        ),
        migrations.AddField(
            model_name="clusterlocation",
            name="world_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clusters",
                to="events.countrylocation",
            ),
        ),
        migrations.CreateModel(
            name="UnitLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unit_id",
                    models.CharField(blank=True, null=True, verbose_name="unit-id"),
                ),
                ("unit_name", models.CharField(max_length=2, verbose_name="unit name")),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="events.chapterlocation",
                    ),
                ),
            ],
            options={
                "unique_together": {("unit_name", "chapter")},
            },
        ),
        migrations.CreateModel(
            name="AreaLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "area_id",
                    models.CharField(blank=True, null=True, verbose_name="area-id"),
                ),
                (
                    "area_name",
                    models.CharField(max_length=150, verbose_name="name-of-area"),
                ),
                (
                    "area_code",
                    models.CharField(
                        max_length=3, null=True, unique=True, verbose_name="area-code"
                    ),
                ),
                (
                    "general_address",
                    models.CharField(
                        help_text="general postcode/address", max_length=100
                    ),
                ),
                ("location_description", models.TextField(blank=True, null=True)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="events.unitlocation",
                    ),
                ),
            ],
            options={
                "unique_together": {("area_name", "unit")},
            },
        ),
        migrations.CreateModel(
            name="YouthCamp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="camp name"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="camp start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="camp end date"
                    ),
                ),
                (
                    "venue_address",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="venue address",
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="venue name"
                    ),
                ),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("AREA", "Area"),
                            ("UNIT", "Unit"),
                            ("CLUSTER", "Cluster"),
                        ],
                        default="AREA",
                        max_length=20,
                        verbose_name="area type",
                    ),
                ),
                (
                    "number_of_pax",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="number of participants"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="camp theme"
                    ),
                ),
                (
                    "anchor_verse",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="anchor verse",
                    ),
                ),
                (
                    "areas_involved",
                    models.ManyToManyField(
                        blank=True,
                        related_name="involved_in_camps",
                        to="events.arealocation",
                    ),
                ),
                (
                    "specific_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="youth_camps",
                        to="events.arealocation",
                    ),
                ),
                (
                    "supervising_chapter_CFC_coordinator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cfc_supervised_youth_camps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="youth CFC coordinator supervisor",
                    ),
                ),
                (
                    "supervising_chapter_youth_head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_youth_camps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="youth chapter head supervisor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YouthCampServiceTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("head_of_role", models.BooleanField(default=False)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_youth_camp_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="service_team_members",
                        to="events.youthcamprole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youth_camp_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "youth_camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_team_members",
                        to="events.youthcamp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Youth Camp Service Team Member",
                "verbose_name_plural": "Youth Camp Service Team Members",
                "unique_together": {("user", "youth_camp")},
            },
        ),
        migrations.AddField(
            model_name="youthcamp",
            name="service_team",
            field=models.ManyToManyField(
                blank=True,
                related_name="youth_camps_service_team",
                through="events.YouthCampServiceTeamMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
