# Generated by Django 5.1.5 on 2025-09-06 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("users", "0002_alergies_emergencycontact_communityuser_alergies_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicEventResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(verbose_name="public resource name"),
                ),
                (
                    "resource_link",
                    models.CharField(
                        blank=True, null=True, verbose_name="public resource link"
                    ),
                ),
                (
                    "resource_file",
                    models.FileField(
                        upload_to="public-event-resources", verbose_name="file resource"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("public_resource", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="eventparticipant",
            name="small_group",
        ),
        migrations.RemoveField(
            model_name="eventparticipant",
            name="team_assignment",
        ),
        migrations.AddField(
            model_name="event",
            name="event_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="event description"
            ),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="data_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="media_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="understood_registration",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="GuestParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("outside_of_country", models.BooleanField(default=False)),
                (
                    "ministry_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YFC", "Youth for Christ"),
                            ("CFC", "Couples for Christ"),
                            ("SFC", "Singles for Christ"),
                            ("KFC", "Kids for Christ"),
                            ("GTY", "Guest Youth"),
                            ("GTA", "Guest Adult"),
                            ("VLN", "Volunteer"),
                            ("VST", "Visitor"),
                            ("OTH", "Other"),
                        ],
                        default="GTY",
                        null=True,
                        verbose_name="Family Ministry",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="participant email address",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="participant phone number",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="participant first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="participant last name",
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="participant middle name",
                    ),
                ),
                (
                    "preferred_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="participant preferred name",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="participant gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Format: YYYY-MM-DD",
                        null=True,
                        verbose_name="participant date of birth",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="guest-event-profile-images/",
                        verbose_name="participant event profile picture",
                    ),
                ),
                (
                    "further_alergy_information",
                    models.TextField(
                        blank=True, null=True, verbose_name="other alergy information"
                    ),
                ),
                (
                    "alergies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_alergies",
                        to="users.alergies",
                        verbose_name="Individual alergies",
                    ),
                ),
                (
                    "chapter",
                    models.ManyToManyField(
                        blank=True,
                        related_name="chapter_events",
                        to="events.chapterlocation",
                    ),
                ),
                (
                    "country_of_origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.countrylocation",
                    ),
                ),
                (
                    "emergency_contacts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="guest_user_emergency_contacts",
                        to="users.emergencycontact",
                        verbose_name="Emergency contacts",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="guest_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_participations",
                to="events.guestparticipant",
            ),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="memo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_memos",
                to="events.publiceventresource",
                verbose_name="main event memo",
            ),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="resources",
            field=models.ManyToManyField(
                blank=True,
                related_name="event_resources",
                to="events.publiceventresource",
            ),
        ),
    ]
