# Generated by Django 5.1.5 on 2025-09-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventparticipant",
            name="memo",
        ),
        migrations.RemoveField(
            model_name="eventparticipant",
            name="resources",
        ),
        migrations.AddField(
            model_name="event",
            name="memo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_memos",
                to="events.publiceventresource",
                verbose_name="main event memo",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="resources",
            field=models.ManyToManyField(
                blank=True,
                related_name="event_resources",
                to="events.publiceventresource",
            ),
        ),
    ]
