# Generated by Django 5.1.5 on 2025-09-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="event end date"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="event start date"
            ),
        ),
    ]
