# Generated by Django 5.1.5 on 2025-09-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_eventparticipant_memo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_code",
            field=models.CharField(blank=True, null=True, verbose_name="event code"),
        ),
    ]
