# Generated by Django 5.1.5 on 2025-09-09 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_code",
            field=models.CharField(
                blank=True,
                help_text="Event code that is shared around and for participant convenience. E.g. CNF26ANCRD - tells you it's a conference in 2026 with the name ANCHORED",
                null=True,
                verbose_name="event code",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                max_length=200, null=True, verbose_name="event name"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name_code",
            field=models.CharField(
                blank=True,
                help_text="Short code for the event name, used in generating the event code E.g. for ANCHORED event, use ANCRD",
                max_length=5,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(5)],
                verbose_name="event name code",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="sentence_description",
            field=models.CharField(
                blank=True,
                help_text="A brief one-sentence description of the event, for promotional purposes. E.g. A youth camp to anchor our faith in Christ.",
                max_length=300,
                null=True,
                verbose_name="sentence description",
            ),
        ),
    ]
