# Generated by Django 5.1.5 on 2025-09-15 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_end_date_alter_event_start_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="supervising_chapter_CFC_coordinator",
        ),
        migrations.RemoveField(
            model_name="event",
            name="supervising_chapter_youth_head",
        ),
        migrations.AddField(
            model_name="event",
            name="supervising_CFC_coordinators",
            field=models.ManyToManyField(
                blank=True,
                related_name="cfc_supervised_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="youth CFC coordinator supervisors",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="supervising_youth_heads",
            field=models.ManyToManyField(
                blank=True,
                related_name="supervised_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="youth chapter head supervisors",
            ),
        ),
    ]
