# Generated by Django 5.1.5 on 2025-09-06 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_event_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestparticipant",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_events",
                to="events.event",
            ),
        ),
    ]
