# Generated by Django 5.1.5 on 2025-09-06 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_guestparticipant_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question_name",
                    models.CharField(max_length=255, verbose_name="name of question"),
                ),
                ("question_body", models.TextField(verbose_name="question proper")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("TEXTAREA", "Text Area"),
                            ("INTEGER", "Integer"),
                            ("BOOLEAN", "Yes/No"),
                            ("CHOICE", "Single Choice"),
                            ("MULTICHOICE", "Multiple Choice"),
                        ],
                        max_length=20,
                        verbose_name="question type",
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_text", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionChoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("value", models.CharField(blank=True, max_length=100, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="eventparticipant",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="eventparticipant",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="unique_event_user_participation"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventparticipant",
            constraint=models.UniqueConstraint(
                fields=("event", "guest_user"), name="unique_event_guest_participation"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventparticipant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("guest_user__isnull", True), ("user__isnull", False)),
                    models.Q(("guest_user__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="either_user_or_guest_only",
            ),
        ),
        migrations.AddField(
            model_name="extraquestion",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_questions",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="events.eventparticipant",
            ),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="events.extraquestion",
            ),
        ),
        migrations.AddField(
            model_name="questionchoice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="events.extraquestion",
            ),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="selected_choices",
            field=models.ManyToManyField(blank=True, to="events.questionchoice"),
        ),
        migrations.AlterUniqueTogether(
            name="questionanswer",
            unique_together={("participant", "question")},
        ),
    ]
