"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/

IMPORTANT - AWS SSM/KMS USAGE:
==============================
ALL secrets are loaded from SSM Parameter Store in a SINGLE batch call at startup.
This prevents KMS quota exhaustion from repeated decrypt operations.

DO NOT add runtime SSM calls anywhere in the application:
- NO get_parameter() calls in views, tasks, or middleware
- ALL secrets must be loaded via get_secret() which uses startup cache
- New secrets must be added to REQUIRED_SECRETS list below

If you need a new secret:
1. Add it to REQUIRED_SECRETS list
2. Access it via get_secret('SECRET_NAME')
3. Never call boto3 SSM client directly
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# AWS Boto
import boto3
from botocore.session import Session
from botocore.exceptions import NoCredentialsError
from botocore.config import Config

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

from django.utils.timezone import get_current_timezone

sentry_sdk.init(
    dsn="https://4350eff86c6b7bf12498665064bf3b1e@o4509949719085056.ingest.de.sentry.io/4509949720330320",
    integrations=[DjangoIntegration()],

    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
    send_default_pii=True,
)

load_dotenv()

SSM_PARAM_SUFFIX = "/prod/amdg/v1/"

# Check if we should use SSM or environment variables
USE_SSM = False
ssm_client = None
_SECRET_CACHE = {}  # In-memory cache for secrets loaded at startup

# Define all required secret keys upfront
REQUIRED_SECRETS = [
    'SECRET_KEY',
    'DEBUG',
    'ALLOWED_HOSTS',
    'DB_ENGINE',
    'DB_NAME',
    'DB_USER',
    'DB_PASSWORD',
    'DB_HOST',
    'DB_PORT',
    'AWS_STORAGE_BUCKET_NAME',
    'AWS_S3_REGION_NAME',
]

try:
    # Try to initialize SSM client and verify AWS credentials
    ssm_client = boto3.client('ssm', region_name='eu-west-2')
    sts = boto3.client('sts')
    sts.get_caller_identity()  # This will raise an exception if credentials are invalid
    # USE_SSM = True # ! Temporarily disabled SSM usage
    print("### Using AWS SSM for secrets ###")
except (NoCredentialsError, Exception) as e:
    print(f"### AWS SSM not available ({type(e).__name__}), using environment variables ###")
    USE_SSM = False

def _load_all_secrets_from_ssm():
    """
    Load ALL secrets from SSM Parameter Store in a SINGLE batch call.
    This executes ONCE at startup to minimize KMS decrypt operations.
    """
    if not USE_SSM or not ssm_client:
        return
    
    try:
        # Build full parameter names with prefix
        param_names = [SSM_PARAM_SUFFIX + name for name in REQUIRED_SECRETS]
        
        # SINGLE batch call to get all parameters
        print(f"### Loading {len(param_names)} secrets from SSM in single batch call ###")
        response = ssm_client.get_parameters(
            Names=param_names,
            WithDecryption=True  # Single KMS decrypt operation for all parameters
        )
        
        # Cache all retrieved parameters
        for param in response['Parameters']:
            # Strip the prefix to get the original key name
            key = param['Name'].replace(SSM_PARAM_SUFFIX, '')
            _SECRET_CACHE[key] = param['Value']
        
        # Check for any missing parameters
        if response.get('InvalidParameters'):
            missing = [p.replace(SSM_PARAM_SUFFIX, '') for p in response['InvalidParameters']]
            print(f"### WARNING: Missing SSM parameters: {missing} ###")
        
        print(f"### Successfully loaded {len(_SECRET_CACHE)} secrets from SSM ###")
        
    except Exception as e:
        print(f"### Failed to batch load secrets from SSM: {e} ###")
        print(f"### Falling back to environment variables ###")

# Load all secrets ONCE at startup
_load_all_secrets_from_ssm()

def get_secret(name):
    """
    Fetch secret from in-memory cache (loaded at startup) or environment variables.
    NO runtime SSM/KMS calls are made - all secrets loaded once at container startup.
    """
    # First check the cache (populated from SSM batch load at startup)
    if name in _SECRET_CACHE:
        return _SECRET_CACHE[name]
    
    # Fall back to environment variables
    value = os.getenv(name)
    if value is None:
        raise ValueError(f"Required secret '{name}' not found in SSM cache or environment variables")
    
    return value

SECRET_KEY = get_secret('SECRET_KEY')
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.getenv("SECRET_KEY", "your-default-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_secret("DEBUG") == "True"

ALLOWED_HOSTS = get_secret("ALLOWED_HOSTS").split(",")

AUTH_USER_MODEL = "users.CommunityUser"



# Application definition

DJANGO_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'storages'
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',
    'django_filters',
    'corsheaders',
    'channels',
    'django_celery_beat',
    'django_celery_results',
]

LOCAL_APPS = [
    "core",
    "apps.users.apps.UsersConfig",
    "apps.events.apps.EventsConfig",
    "apps.shop.apps.ShopConfig",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',    
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",  # Disabled - using JWT tokens instead
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CORS Configuration - Applied globally
CORS_ALLOWED_ORIGINS = [
    'https://cems-nine.vercel.app',
    'https://rsalardadevelop.co.uk',
    'https://www.rsalardadevelop.co.uk',
    'https://rsalardadevelop.com',
    'https://www.rsalardadevelop.com',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

# Additional CORS settings for django-cors-headers
CORS_ALLOWED_ORIGIN_REGEXES = []
CORS_URLS_REGEX = r'^/.*$'  # Apply CORS to ALL URLs (not just /api/)

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Expose custom headers to the frontend
CORS_EXPOSE_HEADERS = [
    'content-type',
]

# Critical: Ensure CORS headers are added to ALL responses (including errors and redirects)
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# CRITICAL FIX: Force CORS headers on redirect responses (301, 302, etc.)
# Without this, browsers reject redirects from missing trailing slashes
CORS_ALLOW_PRIVATE_NETWORK = False  # Explicitly disable to avoid conflicts

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"

# Channel layer configuration for Django Channels
if DEBUG:
    # Development: Use in-memory channel layer (no Redis required)
    print("### DEBUG MODE - Using in-memory channel layer ###")
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
else:
    # Production: Use Redis for channel layer
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [("redis", 6379)],  # Use docker-compose service name
            },
        },
    }

SECURITY_HEADERS = {
    'Cross-Origin-Opener-Policy': 'unsafe-none',  # TEMPORARY for HTTP
}
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': get_secret("DB_ENGINE"),
        'NAME': get_secret("DB_NAME"),
        'USER': get_secret("DB_USER"),
        'PASSWORD': get_secret("DB_PASSWORD"),
        'HOST': get_secret("DB_HOST"),
        'PORT': get_secret("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/London"  # This handles UK timezone including BST automatically

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Static and Media URLs
if not DEBUG:
    AWS_STORAGE_BUCKET_NAME = get_secret("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = get_secret("AWS_S3_REGION_NAME")

    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400"
    }
    # STATICFILES_STORAGE = "core.storage.StaticStorage"
    # DEFAULT_FILE_STORAGE = "core.storage.MediaStorage"

    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
                "OPTIONS": {
                    "bucket_name": AWS_STORAGE_BUCKET_NAME,
                    "region_name": AWS_S3_REGION_NAME,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
                "location": "static",  # Folder in the bucket for static files
                "file_overwrite": False,
        },
    },
    }
    
    AWS_DEFAULT_ACL = None
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }
    # STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

else:
    print("\n ### DEBUG is ON - Local storage in use ### ")
    
    STATIC_URL = "/static/"
    STATIC_ROOT = os.path.join(BASE_DIR, "static")

    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# JWT Authentication Settings moved to REST_FRAMEWORK below

## SECURITY SETTINGS - PRODUCTION & DEVELOPMENT

if not DEBUG:
    print("### PRODUCTION SECURITY SETTINGS ENABLED ###")
    # Production HTTPS settings
    CSRF_TRUSTED_ORIGINS = [
        'https://rsalardadevelop.co.uk',
        'https://www.rsalardadevelop.co.uk',
        'https://rsalardadevelop.com',
        'https://www.rsalardadevelop.com',
        'https://cems-nine.vercel.app'
    ]
    
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # SECURE_SSL_REDIRECT = True
    USE_X_FORWARDED_HOST = True
    
    SESSION_COOKIE_DOMAIN = ".rsalardadevelop.co.uk"
    CSRF_COOKIE_DOMAIN = ".rsalardadevelop.co.uk"
    # CSRF_COOKIE_SECURE = True
    # CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'None'

    
else:
    print("### DEVELOPMENT SECURITY SETTINGS ENABLED ###")
    # Development settings - no CSRF needed with JWT


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,  # items per page
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # Custom JWT Cookie Authentication (HTTPOnly cookies)
        'core.authentication.JWTCookieAuthentication',
        # Fallback to session authentication for admin
    ),
    # WARNING - THIS PERMISSION MUST BE SET TO 'IS_AUTHENTICATED' DURING PRODUCTION TO PROTECT ENDPOINTS
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.AutoSchema',
    # Custom exception handler to ensure CORS works with authentication failures
    'EXCEPTION_HANDLER': 'core.exception_handler.custom_exception_handler',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'My API',
    'DESCRIPTION': 'API documentation',
    'VERSION': '1.0.0',
}

import datetime

SIMPLE_JWT = {
    # Shorter access token lifetime for security
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),  # Removed JWT type as we're using cookies
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': datetime.timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': datetime.timedelta(days=1),
}

JWT_AUTH_COOKIE_SAMESITE = 'None'
JWT_AUTH_COOKIE_SECURE = True

# CSRF Protection DISABLED - Using JWT tokens instead
# JWT tokens in HTTPOnly cookies provide sufficient protection against CSRF
# since the tokens themselves cannot be stolen via XSS attacks

# Session cookie settings (for admin - CSRF still disabled globally)
SESSION_COOKIE_HTTPONLY = True
# Stripe Payment Configuration
# TEST MODE by default - set to False for production
STRIPE_TEST_MODE = os.getenv('STRIPE_TEST_MODE', 'True') == 'True'
STRIPE_SECRET_KEY_TEST = os.getenv('STRIPE_SECRET_KEY_TEST', '')
STRIPE_SECRET_KEY_LIVE = os.getenv('STRIPE_SECRET_KEY_LIVE', '')
STRIPE_PUBLISHABLE_KEY_TEST = os.getenv('STRIPE_PUBLISHABLE_KEY_TEST', '')
STRIPE_PUBLISHABLE_KEY_LIVE = os.getenv('STRIPE_PUBLISHABLE_KEY_LIVE', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@cems.org')

# Template directories
TEMPLATES[0]['DIRS'] = [os.path.join(BASE_DIR, 'templates')]

# ============================================================================
# CELERY CONFIGURATION
# ============================================================================
# Celery uses Redis DB 1 for broker, DB 2 for results
# Django Channels uses Redis DB 0 (default)
# This separation prevents key conflicts between systems

if DEBUG:
    # Development: Execute tasks synchronously (no Redis/worker required)
    print("### DEBUG MODE - Celery tasks run synchronously ###")
    CELERY_TASK_ALWAYS_EAGER = True  # Execute tasks immediately in the same process
    CELERY_TASK_EAGER_PROPAGATES = True  # Propagate exceptions immediately
    CELERY_BROKER_URL = 'memory://'  # In-memory broker
    CELERY_RESULT_BACKEND = 'cache+memory://'  # In-memory results
else:
    # Production: Use Redis and async execution
    CELERY_BROKER_URL = 'redis://redis:6379/1'  # Use docker-compose service name
    CELERY_RESULT_BACKEND = 'django-db'  # Store results in Django database
    CELERY_TASK_ALWAYS_EAGER = False  # Run tasks asynchronously

CELERY_CACHE_BACKEND = 'default'

# Task execution settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit
CELERY_TASK_ACKS_LATE = True  # Acknowledge tasks after completion for safety
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Only fetch one task at a time for long tasks

# Timezone configuration (must match Django's timezone)
CELERY_TIMEZONE = TIME_ZONE  # Use Django's timezone setting
CELERY_ENABLE_UTC = True  # Store all times in UTC

# Result backend settings
CELERY_RESULT_EXTENDED = True  # Store task args/kwargs in results
CELERY_RESULT_EXPIRES = 60 * 60 * 24 * 7  # Results expire after 7 days

# Serialization settings (use JSON for security)
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Beat scheduler configuration
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Task routing and queue configuration
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_DEFAULT_EXCHANGE = 'default'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'default'

# Logging configuration for Celery
CELERY_WORKER_HIJACK_ROOT_LOGGER = False  # Don't hijack Django's logger

# ============================================================================
# END CELERY CONFIGURATION
# ============================================================================