"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# AWS Boto
import boto3
from botocore.session import Session
from botocore.exceptions import NoCredentialsError
from botocore.config import Config

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

from django.utils.timezone import get_current_timezone

sentry_sdk.init(
    dsn="https://4350eff86c6b7bf12498665064bf3b1e@o4509949719085056.ingest.de.sentry.io/4509949720330320",
    integrations=[DjangoIntegration()],

    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
    send_default_pii=True,
)

load_dotenv()

SSM_PARAM_SUFFIX = "/prod/amdg/v1/"

# Check if we should use SSM or environment variables
USE_SSM = False
ssm_client = None

try:
    # Try to initialize SSM client and verify AWS credentials
    ssm_client = boto3.client('ssm', region_name='eu-west-2')
    sts = boto3.client('sts')
    sts.get_caller_identity()  # This will raise an exception if credentials are invalid
    USE_SSM = True
    print("### Using AWS SSM for secrets ###")
except (NoCredentialsError, Exception) as e:
    print(f"### AWS SSM not available ({type(e).__name__}), using environment variables ###")
    USE_SSM = False

def get_secret(name):
    """
    Fetch secret from AWS SSM Parameter Store in production,
    or fall back to environment variables in development/testing.
    """
    if USE_SSM and ssm_client:
        try:
            return ssm_client.get_parameter(
                Name=SSM_PARAM_SUFFIX + name, 
                WithDecryption=True
            )['Parameter']['Value']
        except Exception as e:
            print(f"### Failed to get {name} from SSM, falling back to env: {e} ###")
            return os.getenv(name)
    else:
        # Use environment variables (from .env file or container environment)
        value = os.getenv(name)
        if value is None:
            raise ValueError(f"Required environment variable '{name}' is not set")
        return value

SECRET_KEY = get_secret('SECRET_KEY')
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.getenv("SECRET_KEY", "your-default-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_secret("DEBUG") == "True"

ALLOWED_HOSTS = get_secret("ALLOWED_HOSTS").split(",")

AUTH_USER_MODEL = "users.CommunityUser"



# Application definition

DJANGO_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'storages'
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'django_filters',
    'corsheaders',
    'channels',
    'django_celery_beat',
    'django_celery_results',
]

LOCAL_APPS = [
    "core",
    "apps.users.apps.UsersConfig",
    "apps.events.apps.EventsConfig",
    "apps.shop.apps.ShopConfig",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CORS Configuration - Applied globally
CORS_ALLOWED_ORIGINS = [
    'https://rsalardadevelop.co.uk',
    'https://www.rsalardadevelop.co.uk',
    'https://rsalardadevelop.com',
    'https://www.rsalardadevelop.com',
    'https://cems-nine.vercel.app',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"

# Channel layer configuration for Django Channels
if DEBUG:
    # Development: Use in-memory channel layer (no Redis required)
    print("### DEBUG MODE - Using in-memory channel layer ###")
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
else:
    # Production: Use Redis for channel layer
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [("redis", 6379)],  # Use docker-compose service name
            },
        },
    }

SECURITY_HEADERS = {
    'Cross-Origin-Opener-Policy': 'unsafe-none',  # TEMPORARY for HTTP
}
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': get_secret("DB_ENGINE"),
        'NAME': get_secret("DB_NAME"),
        'USER': get_secret("DB_USER"),
        'PASSWORD': get_secret("DB_PASSWORD"),
        'HOST': get_secret("DB_HOST"),
        'PORT': get_secret("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/London"  # This handles UK timezone including BST automatically

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Static and Media URLs
if not DEBUG:
    AWS_STORAGE_BUCKET_NAME = get_secret("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = get_secret("AWS_S3_REGION_NAME")

    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400"
    }
    STATICFILES_STORAGE = "core.storage.StaticStorage"
    DEFAULT_FILE_STORAGE = "core.storage.MediaStorage"

    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
                "OPTIONS": {
                    "bucket_name": AWS_STORAGE_BUCKET_NAME,
                    "region_name": AWS_S3_REGION_NAME,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
                "location": "static",  # Folder in the bucket for static files
                "default_acl": "public-read",
                "file_overwrite": False,
        },
    },
    }
    
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
        "ACL": "public-read",
    }
    STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

else:
    print("\n ### DEBUG is ON - Local storage in use ### ")
    
    STATIC_URL = "/static/"
    STATIC_ROOT = os.path.join(BASE_DIR, "static")

    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# JWT Authentication Settings moved to REST_FRAMEWORK below

## SECURITY SETTINGS - PRODUCTION & DEVELOPMENT

if not DEBUG:
    # Production HTTPS settings
    CSRF_TRUSTED_ORIGINS = [
        'https://rsalardadevelop.co.uk',
        'https://www.rsalardadevelop.co.uk',
        'https://rsalardadevelop.com',
        'https://www.rsalardadevelop.com',
        'https://cems-nine.vercel.app'
    ]
    
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
else:
    # Development settings
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ]


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,  # items per page
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # Custom JWT Cookie Authentication (HTTPOnly cookies)
        'core.authentication.JWTCookieAuthentication',
        # Fallback to session authentication for admin
        "rest_framework.authentication.SessionAuthentication",
    ),
    # WARNING - THIS PERMISSION MUST BE SET TO 'IS_AUTHENTICATED' DURING PRODUCTION TO PROTECT ENDPOINTS
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'My API',
    'DESCRIPTION': 'API documentation',
    'VERSION': '1.0.0',
}

import datetime

SIMPLE_JWT = {
    # Shorter access token lifetime for security
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),  # Removed JWT type as we're using cookies
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': datetime.timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': datetime.timedelta(days=1),
}

# CSRF Settings for production security
CSRF_COOKIE_HTTPONLY = False  # Must be False so JavaScript can read it for CSRF header
CSRF_COOKIE_SECURE = not DEBUG  # Only send over HTTPS in production
CSRF_COOKIE_SAMESITE = 'Strict'  # Prevent CSRF attacks
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_AGE = 31449600  # 1 year

# Session cookie settings (for admin)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Strict'

# Stripe Payment Configuration
# TEST MODE by default - set to False for production
STRIPE_TEST_MODE = os.getenv('STRIPE_TEST_MODE', 'True') == 'True'
STRIPE_SECRET_KEY_TEST = os.getenv('STRIPE_SECRET_KEY_TEST', '')
STRIPE_SECRET_KEY_LIVE = os.getenv('STRIPE_SECRET_KEY_LIVE', '')
STRIPE_PUBLISHABLE_KEY_TEST = os.getenv('STRIPE_PUBLISHABLE_KEY_TEST', '')
STRIPE_PUBLISHABLE_KEY_LIVE = os.getenv('STRIPE_PUBLISHABLE_KEY_LIVE', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@cems.org')

# Template directories
TEMPLATES[0]['DIRS'] = [os.path.join(BASE_DIR, 'templates')]

# ============================================================================
# CELERY CONFIGURATION
# ============================================================================
# Celery uses Redis DB 1 for broker, DB 2 for results
# Django Channels uses Redis DB 0 (default)
# This separation prevents key conflicts between systems

if DEBUG:
    # Development: Execute tasks synchronously (no Redis/worker required)
    print("### DEBUG MODE - Celery tasks run synchronously ###")
    CELERY_TASK_ALWAYS_EAGER = True  # Execute tasks immediately in the same process
    CELERY_TASK_EAGER_PROPAGATES = True  # Propagate exceptions immediately
    CELERY_BROKER_URL = 'memory://'  # In-memory broker
    CELERY_RESULT_BACKEND = 'cache+memory://'  # In-memory results
else:
    # Production: Use Redis and async execution
    CELERY_BROKER_URL = 'redis://redis:6379/1'  # Use docker-compose service name
    CELERY_RESULT_BACKEND = 'django-db'  # Store results in Django database
    CELERY_TASK_ALWAYS_EAGER = False  # Run tasks asynchronously

CELERY_CACHE_BACKEND = 'default'

# Task execution settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit
CELERY_TASK_ACKS_LATE = True  # Acknowledge tasks after completion for safety
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Only fetch one task at a time for long tasks

# Timezone configuration (must match Django's timezone)
CELERY_TIMEZONE = TIME_ZONE  # Use Django's timezone setting
CELERY_ENABLE_UTC = True  # Store all times in UTC

# Result backend settings
CELERY_RESULT_EXTENDED = True  # Store task args/kwargs in results
CELERY_RESULT_EXPIRES = 60 * 60 * 24 * 7  # Results expire after 7 days

# Serialization settings (use JSON for security)
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Beat scheduler configuration
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Task routing and queue configuration
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_DEFAULT_EXCHANGE = 'default'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'default'

# Logging configuration for Celery
CELERY_WORKER_HIJACK_ROOT_LOGGER = False  # Don't hijack Django's logger

# ============================================================================
# END CELERY CONFIGURATION
# ============================================================================