# Generated by Django 5.1.5 on 2025-12-20 00:25

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "triggers",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="triggers (e.g., peanuts, pollen)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
            ],
            options={
                "verbose_name_plural": "Allergies",
            },
        ),
        migrations.CreateModel(
            name="CommunityRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        choices=[
                            ("MEM", "Member"),
                            ("NAT_HEAD", "National Head"),
                            ("YCOM_NAT_HEAD", "YCOM National Head"),
                            ("MUSIC_NAT_HEAD", "Music Ministry National Head"),
                            ("CLUSTER_HEAD", "Cluster Head"),
                            ("AREA_HEAD", "Area Head"),
                            ("CHAPTER_HEAD", "Chapter Head"),
                            ("HOUSEHOLD_HEAD", "Household Head"),
                            ("SUPPORT_HH_HEAD", "Supporting Household Head"),
                            ("SECTOR_HEAD", "Sector Head"),
                            ("VOLUNTEER", "Volunteer"),
                            ("GUEST", "Guest"),
                            ("EVENT_APPROVER", "Event Approver"),
                            ("EVENT_CREATOR", "Event Creator"),
                            ("COMMUNITY_ADMIN", "Community Admin"),
                        ],
                        default="MEM",
                        max_length=20,
                        verbose_name="role name",
                    ),
                ),
                (
                    "role_description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="role description",
                    ),
                ),
                (
                    "is_core",
                    models.BooleanField(
                        default=False,
                        help_text="Defines if the role is a core role",
                        verbose_name="is core role",
                    ),
                ),
                (
                    "authority_level",
                    models.IntegerField(
                        default=0,
                        help_text="helper field to determine logical ranking of roles if many are assigned (max is 10)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="community authority",
                    ),
                ),
                (
                    "visible_role",
                    models.BooleanField(
                        default=True,
                        verbose_name="defines if this is a public role to see",
                    ),
                ),
            ],
            options={
                "verbose_name": "community role",
                "verbose_name_plural": "community roles",
                "ordering": ["authority_level", "role_name"],
            },
        ),
        migrations.CreateModel(
            name="MedicalCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "triggers",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="triggers (e.g., pollen, dust)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
            ],
            options={
                "verbose_name_plural": "Medical Conditions",
            },
        ),
        migrations.CreateModel(
            name="CommunityUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "member_id",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="member ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="username"
                    ),
                ),
                (
                    "primary_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="primary email address",
                    ),
                ),
                (
                    "secondary_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="secondary email address",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="last name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="middle name"
                    ),
                ),
                (
                    "preferred_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="preferred name",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        max_length=6,
                        null=True,
                        verbose_name="gender",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="age",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Format: YYYY-MM-DD",
                        null=True,
                        verbose_name="date of birth",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff status"),
                ),
                (
                    "is_encoder",
                    models.BooleanField(default=False, verbose_name="encoder status"),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user-profile-images/",
                        verbose_name="user profile picture",
                    ),
                ),
                (
                    "profile_picture_uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="profile picture uploaded at"
                    ),
                ),
                (
                    "ministry",
                    models.CharField(
                        choices=[
                            ("YFC", "Youth for Christ"),
                            ("CFC", "Couples for Christ"),
                            ("SFC", "Singles for Christ"),
                            ("KFC", "Kids for Christ"),
                            ("VLN", "Volunteer"),
                            ("YGT", "Youth Guest"),
                            ("AGT", "Adult Guest"),
                        ],
                        default="YGT",
                        max_length=3,
                        verbose_name="ministry",
                    ),
                ),
                (
                    "user_uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="user uploaded to database at"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="user notes (admin use)"
                    ),
                ),
                (
                    "area_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.arealocation",
                        verbose_name="area of residence",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "community user",
                "verbose_name_plural": "community users",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="emergency contact id",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="last name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="middle name"
                    ),
                ),
                (
                    "preferred_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="preferred name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="emergency contact phone number",
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="secondary phone number",
                    ),
                ),
                (
                    "contact_relationship",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MOTHER", "Mother"),
                            ("FATHER", "Father"),
                            ("GUARDIAN", "Guardian"),
                            ("SPOUSE", "Spouse"),
                            ("HUSBAND", "Husband"),
                            ("WIFE", "Wife"),
                            ("BROTHER", "Brother"),
                            ("SISTER", "Sister"),
                            ("FRIEND", "Friend"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="relationship",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="address"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="primary emergency contact"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="additional notes"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_user_emergency_contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="linked user in the community",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAllergy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MILD", "Mild"),
                            ("MODERATE", "Moderate"),
                            ("SEVERE", "Severe"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MILD",
                        max_length=8,
                    ),
                ),
                ("instructions", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allergy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_links",
                        to="users.allergy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_allergies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "allergy")},
            },
        ),
        migrations.AddField(
            model_name="communityuser",
            name="allergies",
            field=models.ManyToManyField(
                blank=True,
                related_name="allergy_users",
                through="users.UserAllergy",
                to="users.allergy",
            ),
        ),
        migrations.CreateModel(
            name="UserCommunityRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="assigned at"),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional information about this role assignment",
                        null=True,
                        verbose_name="notes",
                    ),
                ),
                (
                    "allowed_organisation_control",
                    models.ManyToManyField(
                        blank=True,
                        help_text="defines what organisations this user has permissions or control to",
                        to="events.organisation",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned by",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_links",
                        to="users.communityrole",
                        verbose_name="role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user community role",
                "verbose_name_plural": "user community roles",
                "ordering": ["-assigned_at"],
                "unique_together": {("user", "role")},
            },
        ),
        migrations.AddField(
            model_name="communityuser",
            name="community_roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="role/s in the community",
                related_name="user_community_roles",
                through="users.UserCommunityRole",
                to="users.communityrole",
            ),
        ),
        migrations.CreateModel(
            name="UserMedicalCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MILD", "Mild"),
                            ("MODERATE", "Moderate"),
                            ("SEVERE", "Severe"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MILD",
                        max_length=10,
                    ),
                ),
                ("instructions", models.TextField(blank=True, null=True)),
                ("date_diagnosed", models.DateField(blank=True, null=True)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_links",
                        to="users.medicalcondition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_medical_conditions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "condition")},
            },
        ),
        migrations.AddField(
            model_name="communityuser",
            name="medical_conditions",
            field=models.ManyToManyField(
                blank=True,
                related_name="condition_users",
                through="users.UserMedicalCondition",
                to="users.medicalcondition",
            ),
        ),
    ]
