# Generated by Django 5.1.5 on 2025-10-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userallergy",
            name="severity",
            field=models.CharField(
                choices=[
                    ("MILD", "Mild"),
                    ("MODERATE", "Moderate"),
                    ("SEVERE", "Severe"),
                    ("CRITICAL", "Critical"),
                ],
                default="MILD",
                max_length=8,
            ),
        ),
    ]
