# Generated by Django 5.1.5 on 2025-10-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_usermedicalcondition_severity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityuser",
            name="ministry",
            field=models.CharField(
                choices=[
                    ("YFC", "Youth for Christ"),
                    ("CFC", "Couples for Christ"),
                    ("SFC", "Singles for Christ"),
                    ("KFC", "Kids for Christ"),
                    ("VLN", "Volunteer"),
                    ("YGT", "Youth Guest"),
                    ("AGT", "Adult Guest"),
                ],
                default="YGT",
                max_length=3,
                verbose_name="ministry",
            ),
        ),
    ]
