# Generated by Django 5.1.5 on 2025-10-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_communityuser_ministry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                max_length=6,
                null=True,
                verbose_name="gender",
            ),
        ),
    ]
