# Generated by Django 5.1.5 on 2025-11-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_communityuser_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityrole",
            name="authority_level",
            field=models.IntegerField(
                default=0,
                help_text="helper field to determine logical ranking of roles if many are assigned",
                verbose_name="community authority",
            ),
        ),
    ]
