# Generated by Django 5.1.5 on 2025-11-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_communityrole_authority_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communityrole",
            options={
                "ordering": ["authority_level", "role_name"],
                "verbose_name": "community role",
                "verbose_name_plural": "community roles",
            },
        ),
    ]
