# Generated by Django 5.1.5 on 2025-11-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0037_event_force_participant_organisation"),
        ("users", "0008_communityrole_visible_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercommunityrole",
            name="allowed_organisation_control",
            field=models.ManyToManyField(
                blank=True,
                help_text="defines what organisations this user has permissions or control to",
                to="events.organisation",
            ),
        ),
    ]
