# Generated by Django 5.1.5 on 2025-11-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_usercommunityrole_allowed_organisation_control"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityrole",
            name="role_name",
            field=models.CharField(
                choices=[
                    ("MEM", "Member"),
                    ("NAT_HEAD", "National Head"),
                    ("YCOM_NAT_HEAD", "YCOM National Head"),
                    ("MUSIC_NAT_HEAD", "Music Ministry National Head"),
                    ("CLUSTER_HEAD", "Cluster Head"),
                    ("AREA_HEAD", "Area Head"),
                    ("CHAPTER_HEAD", "Chapter Head"),
                    ("HOUSEHOLD_HEAD", "Household Head"),
                    ("SUPPORT_HH_HEAD", "Supporting Household Head"),
                    ("SECTOR_HEAD", "Sector Head"),
                    ("VOLUNTEER", "Volunteer"),
                    ("GUEST", "Guest"),
                    ("EVENT_APPROVER", "Event Approver"),
                    ("EVENT_CREATOR", "Event Creator"),
                    ("COMMUNITY_ADMIN", "Community Admin"),
                ],
                default="MEM",
                max_length=20,
                verbose_name="role name",
            ),
        ),
    ]
