# Generated by Django 5.1.5 on 2025-12-20 00:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventProduct",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Product UUID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Product Name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=400, verbose_name="Product Description"
                    ),
                ),
                (
                    "extra_info",
                    models.TextField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Additional Product Information",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Product Cost (£)"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Product Discount (£)",
                    ),
                ),
                (
                    "discount_for_service_team",
                    models.BooleanField(
                        default=False,
                        help_text="Enable special discount for service team members",
                        verbose_name="Discount for Service Team",
                    ),
                ),
                (
                    "service_team_discount_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED", "Fixed Amount"),
                        ],
                        help_text="Type of discount for service team members",
                        max_length=20,
                        null=True,
                        verbose_name="service team discount type",
                    ),
                ),
                (
                    "service_team_discount_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Discount value for service team (percentage or fixed amount)",
                        max_digits=10,
                        null=True,
                        verbose_name="service team discount value",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("clothing", "Clothing"),
                            ("accessories", "Accessories"),
                            ("souvenirs", "Souvenirs"),
                            ("books", "Books"),
                            ("stationery", "Stationery"),
                            ("tech", "Tech Items"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Stock Quantity"
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight this product in the store",
                        verbose_name="Featured Item",
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is available for purchase",
                        verbose_name="In Stock",
                    ),
                ),
                (
                    "colors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of available colors",
                        verbose_name="Available Colors",
                    ),
                ),
                (
                    "maximum_order_quantity",
                    models.IntegerField(
                        default=10, verbose_name="Maximum Order Quantity"
                    ),
                ),
                (
                    "max_purchase_per_person",
                    models.IntegerField(
                        default=-1,
                        help_text="Maximum quantity a person can purchase across all orders. Set to -1 for unlimited.",
                        verbose_name="Maximum Purchase Per Person",
                    ),
                ),
                (
                    "uses_sizes",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this product has size options",
                        verbose_name="Uses Sizes",
                    ),
                ),
                (
                    "only_service_team",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, only service team members can purchase this product",
                        verbose_name="Only for Service Team",
                    ),
                ),
                (
                    "preview_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when product becomes visible but read-only. If not set, product is hidden until release_date.",
                        null=True,
                        verbose_name="Preview Date",
                    ),
                ),
                (
                    "release_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the product becomes available for purchase",
                        null=True,
                        verbose_name="Release Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the product is no longer available for purchase",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone for release and end dates",
                        max_length=50,
                        verbose_name="Event Timezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="EventProductOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_reference_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Order ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "added",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date Added to Cart",
                    ),
                ),
                (
                    "price_at_purchase",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Price at Purchase (£)",
                    ),
                ),
                (
                    "discount_applied",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Discount Applied (£)",
                    ),
                ),
                (
                    "uses_size",
                    models.BooleanField(
                        default=False,
                        help_text="Flags if a size is used for this product order",
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("purchased", "Purchased"),
                            ("cancelled", "Cancelled"),
                            ("pending_refund", "Pending Refund"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Order Status",
                    ),
                ),
                (
                    "refund_status",
                    models.CharField(
                        blank=True,
                        help_text="Tracks refund state: PENDING, IN_PROGRESS, PROCESSED, CANCELLED, FAILED",
                        max_length=20,
                        null=True,
                        verbose_name="Refund Status",
                    ),
                ),
                (
                    "changeable",
                    models.BooleanField(
                        default=True,
                        help_text="Flags if the product order can be changed",
                    ),
                ),
                (
                    "change_requested",
                    models.BooleanField(
                        default=False,
                        help_text="Flags if a change has been requested for this order",
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Reason for Change Request"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes for admin use only",
                        null=True,
                        verbose_name="Admin Notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Product Order",
                "verbose_name_plural": "Event Product Orders",
                "ordering": ["-added"],
            },
        ),
        migrations.CreateModel(
            name="OrderRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for this refund",
                        max_length=100,
                        unique=True,
                        verbose_name="refund reference",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount to be refunded",
                        max_digits=10,
                        verbose_name="refund amount",
                    ),
                ),
                ("currency", models.CharField(default="gbp", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Processing"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PROCESSED", "Refund Processed"),
                            ("CANCELLED", "Refund Cancelled"),
                            ("FAILED", "Refund Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="refund status",
                    ),
                ),
                (
                    "refund_reason",
                    models.CharField(
                        choices=[
                            ("CUSTOMER_REQUESTED", "Customer Requested"),
                            ("WRONG_SIZE", "Wrong Size/Color"),
                            ("DAMAGED_ITEM", "Damaged Item"),
                            ("NOT_AS_DESCRIBED", "Not As Described"),
                            ("DUPLICATE_ORDER", "Duplicate Order"),
                            ("CHANGED_MIND", "Changed Mind"),
                            ("EVENT_CANCELLED", "Event Cancelled"),
                            ("ADMIN_DECISION", "Administrative Decision"),
                            ("OTHER", "Other"),
                        ],
                        default="CUSTOMER_REQUESTED",
                        max_length=50,
                        verbose_name="refund reason",
                    ),
                ),
                (
                    "reason_details",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation for the refund",
                        null=True,
                        verbose_name="detailed reason",
                    ),
                ),
                (
                    "processing_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about refund processing",
                        null=True,
                        verbose_name="processing notes",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address at time of refund creation",
                        max_length=254,
                        null=True,
                        verbose_name="customer email",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        help_text="Full name at time of refund creation",
                        max_length=200,
                        null=True,
                        verbose_name="customer name",
                    ),
                ),
                (
                    "refund_contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address for refund inquiries (event organizer/secretariat)",
                        max_length=254,
                        null=True,
                        verbose_name="refund contact email",
                    ),
                ),
                (
                    "original_payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Payment method used for original transaction",
                        max_length=50,
                        null=True,
                        verbose_name="original payment method",
                    ),
                ),
                (
                    "is_automatic_refund",
                    models.BooleanField(
                        default=False,
                        help_text="True if refund can be processed automatically via Stripe",
                        verbose_name="automatic refund",
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        blank=True,
                        help_text="Method used to process refund (Stripe, Bank Transfer, etc.)",
                        max_length=50,
                        null=True,
                        verbose_name="refund method",
                    ),
                ),
                (
                    "stripe_payment_intent",
                    models.CharField(
                        blank=True,
                        help_text="Original Stripe payment intent ID to refund",
                        max_length=255,
                        null=True,
                        verbose_name="original Stripe payment intent",
                    ),
                ),
                (
                    "stripe_refund_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe refund ID if processed through Stripe",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Stripe refund ID",
                    ),
                ),
                (
                    "stripe_failure_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason if Stripe refund failed",
                        null=True,
                        verbose_name="Stripe failure reason",
                    ),
                ),
                (
                    "stock_restored",
                    models.BooleanField(
                        default=False,
                        help_text="Whether product stock has been restored",
                        verbose_name="stock restored",
                    ),
                ),
                (
                    "stock_restored_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="stock restored at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when refund was marked as processed",
                        null=True,
                        verbose_name="processed at",
                    ),
                ),
                (
                    "customer_notified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether customer has been notified about the refund",
                        verbose_name="customer notified",
                    ),
                ),
                (
                    "admin_notified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether admin/organizer has been notified",
                        verbose_name="admin notified",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Refund",
                "verbose_name_plural": "Order Refunds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="name of category")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="category description",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product categories",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="product image uuid",
                    ),
                ),
                ("image", models.ImageField(upload_to="event-product-images/")),
            ],
        ),
        migrations.CreateModel(
            name="ProductMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="name of material")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="material description",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product materials",
            },
        ),
        migrations.CreateModel(
            name="ProductPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_reference_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Payment ID",
                    ),
                ),
                (
                    "bank_reference",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        null=True,
                        unique=True,
                        verbose_name="Bank Transfer Reference",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Last Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email for order confirmation and communication",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                (
                    "stripe_payment_intent",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount in pounds (e.g., 30.00 for £30.00)",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="gbp", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("REFUND_PROCESSING", "Refund Processing"),
                            ("REFUNDED", "Refunded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False,
                        help_text="Flags if the payment has been approved",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about the payment",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Payment",
                "verbose_name_plural": "Product Payments",
            },
        ),
        migrations.CreateModel(
            name="ProductPaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        help_text="E.g., 'created', 'status_changed', 'approved', 'refunded'",
                        max_length=50,
                        verbose_name="action",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=50, null=True)),
                ("new_status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional context or details"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional structured data"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Payment Log",
                "verbose_name_plural": "Product Payment Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ProductPaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("STRIPE", "Stripe"),
                            ("BANK", "Bank Transfer"),
                            ("CASH", "Cash / In-Person"),
                            ("PAYPAL", "PayPal"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="account name",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="account number",
                    ),
                ),
                (
                    "sort_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="sort code"
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="IBAN"
                    ),
                ),
                (
                    "swift_bic",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="SWIFT/BIC"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="E.g., 'Reference your full name when making the transfer'",
                        null=True,
                        verbose_name="payment instructions",
                    ),
                ),
                (
                    "supports_automatic_refunds",
                    models.BooleanField(
                        default=False,
                        help_text="Enable for Stripe/PayPal. Disable for manual methods like bank transfer or cash.",
                        verbose_name="supports automatic refunds",
                    ),
                ),
                (
                    "refund_contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address participants should contact for refund inquiries (leave blank to use secretariat)",
                        max_length=254,
                        null=True,
                        verbose_name="refund contact email",
                    ),
                ),
                (
                    "refund_processing_time",
                    models.CharField(
                        blank=True,
                        help_text="E.g., '5-7 business days' - displayed to participants",
                        max_length=200,
                        null=True,
                        verbose_name="refund processing time",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Payment Method",
                "verbose_name_plural": "Product Payment Methods",
            },
        ),
        migrations.CreateModel(
            name="ProductPaymentPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="package name")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="package description"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in pounds (e.g., 25.00 for £25.00)",
                        max_digits=10,
                        verbose_name="price",
                    ),
                ),
                ("currency", models.CharField(default="gbp", max_length=10)),
                (
                    "available_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="available from"
                    ),
                ),
                (
                    "available_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="available until"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Payment Package",
                "verbose_name_plural": "Product Payment Packages",
            },
        ),
        migrations.CreateModel(
            name="ProductPurchaseTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_purchased",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total quantity purchased by this user for this product",
                        verbose_name="Total Purchased",
                    ),
                ),
                (
                    "last_purchase_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the user last purchased this product",
                        verbose_name="Last Purchase Date",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Purchase Tracker",
                "verbose_name_plural": "Product Purchase Trackers",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of items available in this size.",
                        verbose_name="Quantity in stock",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XS", "Extra Small"),
                            ("SM", "Small"),
                            ("MD", "Medium"),
                            ("LG", "Large"),
                            ("XL", "Extra Large"),
                        ],
                        default="MD",
                        max_length=5,
                        verbose_name="Size",
                    ),
                ),
                (
                    "price_modifier",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Additional cost for this size, e.g. larger sizes may cost more.",
                        max_digits=10,
                        verbose_name="Price Modifier (£)",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product sizes",
            },
        ),
        migrations.CreateModel(
            name="EventCart",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Cart UUID",
                    ),
                ),
                (
                    "order_reference_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Order ID",
                    ),
                ),
                ("total", models.FloatField(default=0, verbose_name="Total Cost")),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Shipping Cost",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, help_text="Flags if the cart has been approved"
                    ),
                ),
                (
                    "submitted",
                    models.BooleanField(
                        default=False, help_text="Flags if the cart has been submitted"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Flags if the cart is active"
                    ),
                ),
                (
                    "created_via_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Flags if the cart was created by an admin/event organiser",
                    ),
                ),
                (
                    "cart_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("locked", "Locked - In Checkout"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("pending_refund", "Pending Refund"),
                            ("refunded", "Refunded"),
                        ],
                        default="active",
                        help_text="Current status of the cart",
                        max_length=20,
                        verbose_name="Cart Status",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the cart was locked for checkout",
                        null=True,
                        verbose_name="Locked At",
                    ),
                ),
                (
                    "lock_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the cart lock expires (typically 15 minutes)",
                        null=True,
                        verbose_name="Lock Expires At",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Cart Notes"),
                ),
                (
                    "shipping_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Shipping Address"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Cart",
                "verbose_name_plural": "Event Carts",
                "ordering": ["-created"],
            },
        ),
    ]
