# Generated by Django 5.1.5 on 2025-12-20 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="events.event",
                verbose_name="Event Associated With This Product",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Seller That Has Created This Product",
            ),
        ),
        migrations.AddField(
            model_name="eventproductorder",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="shop.eventcart",
            ),
        ),
        migrations.AddField(
            model_name="eventproductorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="shop.eventproduct",
            ),
        ),
        migrations.AddField(
            model_name="eventcart",
            name="products",
            field=models.ManyToManyField(
                related_name="carts",
                through="shop.EventProductOrder",
                to="shop.eventproduct",
                verbose_name="Products",
            ),
        ),
        migrations.AddField(
            model_name="orderrefund",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refunds",
                to="shop.eventcart",
                verbose_name="cart/order",
            ),
        ),
        migrations.AddField(
            model_name="orderrefund",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_refunds",
                to="events.event",
                verbose_name="event",
            ),
        ),
        migrations.AddField(
            model_name="orderrefund",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_refunds_initiated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="initiated by",
            ),
        ),
        migrations.AddField(
            model_name="orderrefund",
            name="participant_refund",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent participant refund if this is part of a full participant removal",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_refunds",
                to="events.participantrefund",
                verbose_name="participant refund",
            ),
        ),
        migrations.AddField(
            model_name="orderrefund",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_refunds_processed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="processed by",
            ),
        ),
        migrations.AddField(
            model_name="orderrefund",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_refunds",
                to=settings.AUTH_USER_MODEL,
                verbose_name="customer",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="shop.productcategory", verbose_name="Categories"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="shop.eventproduct",
                verbose_name="product linked to",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="materials",
            field=models.ManyToManyField(
                blank=True, to="shop.productmaterial", verbose_name="Materials"
            ),
        ),
        migrations.AddField(
            model_name="productpayment",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_payments",
                to="shop.eventcart",
            ),
        ),
        migrations.AddField(
            model_name="productpayment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderrefund",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_refunds",
                to="shop.productpayment",
                verbose_name="original payment",
            ),
        ),
        migrations.AddField(
            model_name="productpaymentlog",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="shop.productpayment",
                verbose_name="payment",
            ),
        ),
        migrations.AddField(
            model_name="productpaymentlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user who performed action",
            ),
        ),
        migrations.AddField(
            model_name="productpaymentmethod",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_payment_methods",
                to="events.event",
                verbose_name="event",
            ),
        ),
        migrations.AddField(
            model_name="productpayment",
            name="method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="shop.productpaymentmethod",
                verbose_name="payment method",
            ),
        ),
        migrations.AddField(
            model_name="productpaymentpackage",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_payment_packages",
                to="events.event",
                verbose_name="event",
            ),
        ),
        migrations.AddField(
            model_name="productpaymentpackage",
            name="products",
            field=models.ManyToManyField(
                blank=True, to="shop.eventproduct", verbose_name="products in package"
            ),
        ),
        migrations.AddField(
            model_name="productpayment",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="shop.productpaymentpackage",
                verbose_name="selected package",
            ),
        ),
        migrations.AddField(
            model_name="productpurchasetracker",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_trackers",
                to="shop.eventproduct",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="productpurchasetracker",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_purchase_trackers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="productsize",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_sizes",
                to="shop.eventproduct",
                verbose_name="product linked to",
            ),
        ),
        migrations.AddField(
            model_name="eventproductorder",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.productsize",
                verbose_name="Product Size",
            ),
        ),
        migrations.AddIndex(
            model_name="orderrefund",
            index=models.Index(
                fields=["status", "-created_at"], name="shop_orderr_status_756a18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderrefund",
            index=models.Index(
                fields=["event", "status"], name="shop_orderr_event_i_1b6cf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderrefund",
            index=models.Index(fields=["cart"], name="shop_orderr_cart_id_31aa5a_idx"),
        ),
        migrations.AddIndex(
            model_name="orderrefund",
            index=models.Index(fields=["user"], name="shop_orderr_user_id_fecc1d_idx"),
        ),
        migrations.AddIndex(
            model_name="orderrefund",
            index=models.Index(
                fields=["refund_reference"], name="shop_orderr_refund__d1e14f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productpaymentlog",
            index=models.Index(
                fields=["payment", "-timestamp"], name="shop_produc_payment_a05f05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productpaymentlog",
            index=models.Index(
                fields=["action", "-timestamp"], name="shop_produc_action_b0bff8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productpurchasetracker",
            index=models.Index(
                fields=["user", "product"], name="shop_produc_user_id_20ace4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productpurchasetracker",
            unique_together={("user", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="productsize",
            unique_together={("product", "size")},
        ),
    ]
