# Generated by Django 5.1.5 on 2025-09-15 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproductorder",
            name="time_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="eventproductorder",
            name="uses_size",
            field=models.BooleanField(
                default=False,
                help_text="Flags if a size is used for this product order",
            ),
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XS", "Extra Small"),
                            ("SM", "Small"),
                            ("MD", "Medium"),
                            ("LG", "Large"),
                            ("XL", "Extra Large"),
                        ],
                        default="MD",
                        max_length=5,
                        verbose_name="Size",
                    ),
                ),
                (
                    "price_modifier",
                    models.FloatField(
                        default=0,
                        help_text="Additional cost for this size, e.g. larger sizes may cost more.",
                        verbose_name="Price Modifier (£)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_sizes",
                        to="shop.eventproduct",
                        verbose_name="product linked to",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product sizes",
            },
        ),
        migrations.AddField(
            model_name="eventproductorder",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.productsize",
                verbose_name="Product Size",
            ),
        ),
    ]
