# Generated by Django 5.1.5 on 2025-09-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_eventproductorder_time_added_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventproduct",
            name="size",
        ),
    ]
