# Generated by Django 5.1.5 on 2025-09-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_remove_eventproduct_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproduct",
            name="maximum_order_quantity",
            field=models.IntegerField(
                default=10, verbose_name="Maximum Order Quantity"
            ),
        ),
    ]
