# Generated by Django 5.1.5 on 2025-09-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_eventproduct_maximum_order_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproduct",
            name="category",
            field=models.CharField(
                choices=[
                    ("clothing", "Clothing"),
                    ("accessories", "Accessories"),
                    ("souvenirs", "Souvenirs"),
                    ("books", "Books"),
                    ("stationery", "Stationery"),
                    ("tech", "Tech Items"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="colors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of available colors",
                verbose_name="Available Colors",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Highlight this product in the store",
                verbose_name="Featured Item",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to product image",
                null=True,
                verbose_name="Product Image URL",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="in_stock",
            field=models.BooleanField(
                default=True,
                help_text="Whether this item is available for purchase",
                verbose_name="In Stock",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="sizes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of available sizes",
                verbose_name="Available Sizes",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="Stock Quantity"),
        ),
    ]
