# Generated by Django 5.1.5 on 2025-09-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_eventproduct_category_eventproduct_colors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventproduct",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to product image",
                max_length=500,
                null=True,
                verbose_name="Product Image URL",
            ),
        ),
    ]
