# Generated by Django 5.1.5 on 2025-09-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_eventproduct_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproduct",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload product image file",
                null=True,
                upload_to="product-images/",
                verbose_name="Product Image",
            ),
        ),
    ]
