# Generated by Django 5.1.5 on 2025-09-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_eventproduct_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventproduct",
            name="image",
        ),
        migrations.RemoveField(
            model_name="eventproduct",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="eventproduct",
            name="sizes",
        ),
    ]
