# Generated by Django 5.1.5 on 2025-09-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_remove_eventproduct_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcart",
            name="order_reference_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Order ID",
            ),
        ),
        migrations.AddField(
            model_name="eventproductorder",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes for admin use only",
                null=True,
                verbose_name="Admin Notes",
            ),
        ),
        migrations.AddField(
            model_name="eventproductorder",
            name="change_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reason for Change Request"
            ),
        ),
        migrations.AddField(
            model_name="eventproductorder",
            name="change_requested",
            field=models.BooleanField(
                default=False,
                help_text="Flags if a change has been requested for this order",
            ),
        ),
        migrations.AddField(
            model_name="eventproductorder",
            name="changeable",
            field=models.BooleanField(
                default=True, help_text="Flags if the product order can be changed"
            ),
        ),
        migrations.AddField(
            model_name="eventproductorder",
            name="order_reference_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Order ID",
            ),
        ),
        migrations.AddField(
            model_name="productpayment",
            name="approved",
            field=models.BooleanField(
                default=False, help_text="Flags if the payment has been approved"
            ),
        ),
        migrations.AddField(
            model_name="productpayment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productpayment",
            name="payment_reference_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Payment ID",
            ),
        ),
    ]
