# Generated by Django 5.1.5 on 2025-10-01 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_participantquestion_answered_by"),
        ("shop", "0009_eventcart_order_reference_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpaymentmethod",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_payment_methods",
                to="events.event",
                verbose_name="event",
            ),
        ),
    ]
