# Generated by Django 5.1.5 on 2025-10-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_productpaymentmethod_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpayment",
            name="bank_reference",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                unique=True,
                verbose_name="Bank Transfer Reference",
            ),
        ),
    ]
