# Generated by Django 5.1.5 on 2025-10-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_productpayment_bank_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcart",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Shipping Cost",
            ),
        ),
        migrations.AlterField(
            model_name="eventproduct",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Product Discount (£)",
            ),
        ),
        migrations.AlterField(
            model_name="eventproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Product Cost (£)"
            ),
        ),
        migrations.AlterField(
            model_name="eventproductorder",
            name="discount_applied",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Discount Applied (£)",
            ),
        ),
        migrations.AlterField(
            model_name="eventproductorder",
            name="price_at_purchase",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price at Purchase (£)",
            ),
        ),
        migrations.AlterField(
            model_name="productpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount in pounds (e.g., 30.00 for £30.00)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="productpaymentpackage",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price in pounds (e.g., 25.00 for £25.00)",
                max_digits=10,
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="price_modifier",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Additional cost for this size, e.g. larger sizes may cost more.",
                max_digits=10,
                verbose_name="Price Modifier (£)",
            ),
        ),
    ]
