# Generated by Django 5.1.5 on 2025-10-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_eventcart_shipping_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcart",
            name="created_via_admin",
            field=models.BooleanField(
                default=False,
                help_text="Flags if the cart was created by an admin/event organiser",
            ),
        ),
    ]
