# Generated by Django 5.1.5 on 2025-11-10 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_productpayment_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcart",
            name="cart_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("locked", "Locked - In Checkout"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                help_text="Current status of the cart",
                max_length=20,
                verbose_name="Cart Status",
            ),
        ),
        migrations.AddField(
            model_name="eventcart",
            name="lock_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the cart lock expires (typically 15 minutes)",
                null=True,
                verbose_name="Lock Expires At",
            ),
        ),
        migrations.AddField(
            model_name="eventcart",
            name="locked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the cart was locked for checkout",
                null=True,
                verbose_name="Locked At",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="max_purchase_per_person",
            field=models.IntegerField(
                default=-1,
                help_text="Maximum quantity a person can purchase across all orders. Set to -1 for unlimited.",
                verbose_name="Maximum Purchase Per Person",
            ),
        ),
        migrations.AddField(
            model_name="productpayment",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email for order confirmation and communication",
                max_length=254,
                verbose_name="Email",
            ),
        ),
        migrations.AddField(
            model_name="productpayment",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="First Name"
            ),
        ),
        migrations.AddField(
            model_name="productpayment",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Last Name"
            ),
        ),
        migrations.AddField(
            model_name="productpayment",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone Number"
            ),
        ),
        migrations.CreateModel(
            name="ProductPaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        help_text="E.g., 'created', 'status_changed', 'approved', 'refunded'",
                        max_length=50,
                        verbose_name="action",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=50, null=True)),
                ("new_status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional context or details"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional structured data"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="shop.productpayment",
                        verbose_name="payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user who performed action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Payment Log",
                "verbose_name_plural": "Product Payment Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["payment", "-timestamp"],
                        name="shop_produc_payment_a05f05_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="shop_produc_action_b0bff8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductPurchaseTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_purchased",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total quantity purchased by this user for this product",
                        verbose_name="Total Purchased",
                    ),
                ),
                (
                    "last_purchase_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the user last purchased this product",
                        verbose_name="Last Purchase Date",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_trackers",
                        to="shop.eventproduct",
                        verbose_name="Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_purchase_trackers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Purchase Tracker",
                "verbose_name_plural": "Product Purchase Trackers",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "product"],
                        name="shop_produc_user_id_20ace4_idx",
                    )
                ],
                "unique_together": {("user", "product")},
            },
        ),
    ]
