# Generated by Django 5.1.5 on 2025-11-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_eventcart_cart_status_eventcart_lock_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpaymentmethod",
            name="refund_contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address participants should contact for refund inquiries (leave blank to use secretariat)",
                max_length=254,
                null=True,
                verbose_name="refund contact email",
            ),
        ),
        migrations.AddField(
            model_name="productpaymentmethod",
            name="refund_processing_time",
            field=models.CharField(
                blank=True,
                help_text="E.g., '5-7 business days' - displayed to participants",
                max_length=200,
                null=True,
                verbose_name="refund processing time",
            ),
        ),
        migrations.AddField(
            model_name="productpaymentmethod",
            name="supports_automatic_refunds",
            field=models.BooleanField(
                default=False,
                help_text="Enable for Stripe/PayPal. Disable for manual methods like bank transfer or cash.",
                verbose_name="supports automatic refunds",
            ),
        ),
    ]
