# Generated by Django 5.1.5 on 2025-11-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_productpaymentmethod_refund_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproduct",
            name="discount_for_service_team",
            field=models.BooleanField(
                default=False,
                help_text="Enable special discount for service team members",
                verbose_name="Discount for Service Team",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="service_team_discount_type",
            field=models.CharField(
                blank=True,
                choices=[("PERCENTAGE", "Percentage"), ("FIXED", "Fixed Amount")],
                help_text="Type of discount for service team members",
                max_length=20,
                null=True,
                verbose_name="service team discount type",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="service_team_discount_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Discount value for service team (percentage or fixed amount)",
                max_digits=10,
                null=True,
                verbose_name="service team discount value",
            ),
        ),
    ]
