# Generated by Django 5.1.5 on 2025-11-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_eventproduct_discount_for_service_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproduct",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the product is no longer available for purchase",
                null=True,
                verbose_name="End Date",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="only_service_team",
            field=models.BooleanField(
                default=False,
                help_text="If checked, only service team members can purchase this product",
                verbose_name="Only for Service Team",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="release_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the product becomes available for purchase",
                null=True,
                verbose_name="Release Date",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Timezone for release and end dates",
                max_length=50,
                verbose_name="Event Timezone",
            ),
        ),
        migrations.AddField(
            model_name="eventproduct",
            name="uses_sizes",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this product has size options",
                verbose_name="Uses Sizes",
            ),
        ),
    ]
