# Generated by Django 5.1.5 on 2025-11-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_eventproduct_end_date_eventproduct_only_service_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproduct",
            name="preview_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when product becomes visible but read-only. If not set, product is hidden until release_date.",
                null=True,
                verbose_name="Preview Date",
            ),
        ),
    ]
