# Generated by Django 5.1.5 on 2025-11-30 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0049_event_date_for_deletion_alter_event_status"),
        ("shop", "0019_eventproduct_preview_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcart",
            name="cart_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("locked", "Locked - In Checkout"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="active",
                help_text="Current status of the cart",
                max_length=20,
                verbose_name="Cart Status",
            ),
        ),
        migrations.CreateModel(
            name="OrderRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for this refund",
                        max_length=100,
                        unique=True,
                        verbose_name="refund reference",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount to be refunded",
                        max_digits=10,
                        verbose_name="refund amount",
                    ),
                ),
                ("currency", models.CharField(default="gbp", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Processing"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PROCESSED", "Refund Processed"),
                            ("CANCELLED", "Refund Cancelled"),
                            ("FAILED", "Refund Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="refund status",
                    ),
                ),
                (
                    "refund_reason",
                    models.CharField(
                        choices=[
                            ("CUSTOMER_REQUESTED", "Customer Requested"),
                            ("WRONG_SIZE", "Wrong Size/Color"),
                            ("DAMAGED_ITEM", "Damaged Item"),
                            ("NOT_AS_DESCRIBED", "Not As Described"),
                            ("DUPLICATE_ORDER", "Duplicate Order"),
                            ("CHANGED_MIND", "Changed Mind"),
                            ("EVENT_CANCELLED", "Event Cancelled"),
                            ("ADMIN_DECISION", "Administrative Decision"),
                            ("OTHER", "Other"),
                        ],
                        default="CUSTOMER_REQUESTED",
                        max_length=50,
                        verbose_name="refund reason",
                    ),
                ),
                (
                    "reason_details",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation for the refund",
                        null=True,
                        verbose_name="detailed reason",
                    ),
                ),
                (
                    "processing_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about refund processing",
                        null=True,
                        verbose_name="processing notes",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address at time of refund creation",
                        max_length=254,
                        null=True,
                        verbose_name="customer email",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        help_text="Full name at time of refund creation",
                        max_length=200,
                        null=True,
                        verbose_name="customer name",
                    ),
                ),
                (
                    "refund_contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address for refund inquiries (event organizer/secretariat)",
                        max_length=254,
                        null=True,
                        verbose_name="refund contact email",
                    ),
                ),
                (
                    "original_payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Payment method used for original transaction",
                        max_length=50,
                        null=True,
                        verbose_name="original payment method",
                    ),
                ),
                (
                    "is_automatic_refund",
                    models.BooleanField(
                        default=False,
                        help_text="True if refund can be processed automatically via Stripe",
                        verbose_name="automatic refund",
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        blank=True,
                        help_text="Method used to process refund (Stripe, Bank Transfer, etc.)",
                        max_length=50,
                        null=True,
                        verbose_name="refund method",
                    ),
                ),
                (
                    "stripe_payment_intent",
                    models.CharField(
                        blank=True,
                        help_text="Original Stripe payment intent ID to refund",
                        max_length=255,
                        null=True,
                        verbose_name="original Stripe payment intent",
                    ),
                ),
                (
                    "stripe_refund_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe refund ID if processed through Stripe",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Stripe refund ID",
                    ),
                ),
                (
                    "stripe_failure_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason if Stripe refund failed",
                        null=True,
                        verbose_name="Stripe failure reason",
                    ),
                ),
                (
                    "bank_account_name",
                    models.CharField(
                        blank=True,
                        help_text="Customer's bank account name for manual refunds",
                        max_length=200,
                        null=True,
                        verbose_name="bank account name",
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="bank account number",
                    ),
                ),
                (
                    "bank_sort_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="bank sort code",
                    ),
                ),
                (
                    "stock_restored",
                    models.BooleanField(
                        default=False,
                        help_text="Whether product stock has been restored",
                        verbose_name="stock restored",
                    ),
                ),
                (
                    "stock_restored_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="stock restored at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when refund was marked as processed",
                        null=True,
                        verbose_name="processed at",
                    ),
                ),
                (
                    "customer_notified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether customer has been notified about the refund",
                        verbose_name="customer notified",
                    ),
                ),
                (
                    "admin_notified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether admin/organizer has been notified",
                        verbose_name="admin notified",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="shop.eventcart",
                        verbose_name="cart/order",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_refunds",
                        to="events.event",
                        verbose_name="event",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_refunds_initiated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="initiated by",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_refunds",
                        to="shop.productpayment",
                        verbose_name="original payment",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_refunds_processed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="processed by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Refund",
                "verbose_name_plural": "Order Refunds",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="shop_orderr_status_756a18_idx",
                    ),
                    models.Index(
                        fields=["event", "status"],
                        name="shop_orderr_event_i_1b6cf7_idx",
                    ),
                    models.Index(
                        fields=["cart"], name="shop_orderr_cart_id_31aa5a_idx"
                    ),
                    models.Index(
                        fields=["user"], name="shop_orderr_user_id_fecc1d_idx"
                    ),
                    models.Index(
                        fields=["refund_reference"],
                        name="shop_orderr_refund__d1e14f_idx",
                    ),
                ],
            },
        ),
    ]
