# Generated by Django 5.1.5 on 2025-11-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_alter_eventcart_cart_status_orderrefund"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproductorder",
            name="refund_status",
            field=models.CharField(
                blank=True,
                help_text="Tracks refund state: PENDING, IN_PROGRESS, PROCESSED, CANCELLED, FAILED",
                max_length=20,
                null=True,
                verbose_name="Refund Status",
            ),
        ),
        migrations.AlterField(
            model_name="eventcart",
            name="cart_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("locked", "Locked - In Checkout"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                    ("refund_in_progress", "Refund In Progress"),
                    ("refunded", "Refunded"),
                ],
                default="active",
                help_text="Current status of the cart",
                max_length=20,
                verbose_name="Cart Status",
            ),
        ),
        migrations.AlterField(
            model_name="eventproductorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("purchased", "Purchased"),
                    ("cancelled", "Cancelled"),
                    ("refund_in_progress", "Refund In Progress"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Order Status",
            ),
        ),
    ]
