# Generated by Django 5.1.5 on 2025-11-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_eventproductorder_refund_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcart",
            name="cart_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("locked", "Locked - In Checkout"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                    ("pending_refund", "Pending Refund"),
                    ("refunded", "Refunded"),
                ],
                default="active",
                help_text="Current status of the cart",
                max_length=20,
                verbose_name="Cart Status",
            ),
        ),
        migrations.AlterField(
            model_name="eventproductorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("purchased", "Purchased"),
                    ("cancelled", "Cancelled"),
                    ("pending_refund", "Pending Refund"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Order Status",
            ),
        ),
    ]
