# Generated by Django 5.1.5 on 2025-11-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_alter_eventcart_cart_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpayment",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes about the payment", null=True
            ),
        ),
    ]
