# Generated by Django 5.1.5 on 2025-11-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_productpayment_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("REFUND_PROCESSING", "Refund Processing"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
