# Generated by Django 5.1.5 on 2025-12-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0025_alter_productpayment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderrefund",
            name="bank_account_name",
        ),
        migrations.RemoveField(
            model_name="orderrefund",
            name="bank_account_number",
        ),
        migrations.RemoveField(
            model_name="orderrefund",
            name="bank_sort_code",
        ),
    ]
