# Generated by Django 5.1.5 on 2025-12-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0052_remove_participantrefund_bank_account_name_and_more"),
        ("shop", "0026_remove_orderrefund_bank_account_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderrefund",
            name="participant_refund",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent participant refund if this is part of a full participant removal",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_refunds",
                to="events.participantrefund",
                verbose_name="participant refund",
            ),
        ),
    ]
